import React,{useState} from "react";
import {ArrowRight,Check,ChevronRight,DoorOpen,Gauge,GitCompareArrows,Network,RefreshCcw,SlidersHorizontal,Sparkles,Target} from "lucide-react";
import {ADJUSTMENT,EXAMPLE_GROUPS,PUPPY_CHOICES,SAVINGS_AFTER,SAVINGS_BEFORE,TARGET_COMPARISONS} from "./lesson5TeachingData.js";

function Question({icon:Icon,eyebrow,children}){return <header className="l5-question"><span><Icon/></span><div><small>{eyebrow}</small><h2>{children}</h2></div></header>}
function Takeaway({children}){return <div className="l5-takeaway" role="status"><Check/><p>{children}</p></div>}
function Bridge({children}){return <div className="l5-bridge"><ChevronRight/><p>{children}</p></div>}
function Probabilities({items,target="ball"}){return <div className="l5-probabilities">{items.map(item=><div key={item.token} className={item.token===target?"is-target":""}><span>{item.token}</span><i><b style={{"--value":`${item.probability}%`}}/></i><strong>{item.probability}%</strong></div>)}</div>}

export function Lesson5Page1({active,t,onComplete}){const[pick,setPick]=useState("");const[revealed,setRevealed]=useState(false);function reveal(){if(!pick)return;setRevealed(true);onComplete?.()}return <section hidden={!active} className="lesson-5-page"><Question icon={Target} eyebrow={t("mission5.page1.eyebrow")}>{t("mission5.page1.question")}</Question><p className="l5-intro">{t("mission5.page1.intro")}</p><div className="l5-practice-machine"><div className="l5-example-card"><small>{t("mission5.page1.trainingText")}</small><strong>The puppy chased the <em>___</em></strong></div><ArrowRight/><div className="l5-choice-tray" role="group" aria-label={t("mission5.page1.action")}>{PUPPY_CHOICES.map(word=><button type="button" aria-pressed={pick===word} onClick={()=>{setPick(word);setRevealed(false)}} key={word}>{word}</button>)}</div><button className="primary" type="button" disabled={!pick} onClick={reveal}>{t("mission5.actions.check")}</button><img src="/assets/img/mission5-robot-training.png" alt="" aria-hidden="true"/></div>{revealed&&<div className="l5-target-reveal" aria-live="polite"><span>{t("mission5.page1.predicted")} <b>{pick}</b></span><ArrowRight/><span>{t("mission5.page1.actual")} <b>ball</b></span></div>}<p className="l5-label">{t("mission5.labels.classroom")}</p>{revealed&&<Takeaway>{t("mission5.page1.takeaway")}</Takeaway>}<Bridge>{t("mission5.page1.bridge")}</Bridge></section>}

export function Lesson5Page2({active,t,onComplete}){const[seen,setSeen]=useState(new Set());const[mode,setMode]=useState("low");function inspect(next){setMode(next);setSeen(current=>{const updated=new Set(current).add(next);if(updated.size===2)onComplete?.();return updated})}return <section hidden={!active} className="lesson-5-page"><Question icon={GitCompareArrows} eyebrow={t("mission5.page2.eyebrow")}>{t("mission5.page2.question")}</Question><p className="l5-intro">{t("mission5.page2.intro")}</p><div className="l5-compare-tabs" role="tablist"><button role="tab" aria-selected={mode==="low"} onClick={()=>inspect("low")}>{t("mission5.page2.stateA")}</button><button role="tab" aria-selected={mode==="high"} onClick={()=>inspect("high")}>{t("mission5.page2.stateB")}</button></div><div className="l5-compare-scene"><div><small>{t("mission5.page2.beforeCorrection")}</small><Probabilities items={TARGET_COMPARISONS[mode]}/></div><ArrowRight/><div className="l5-answer-flap"><small>{t("mission5.page2.actual")}</small><strong>ball</strong><span>{mode==="high"?t("mission5.page2.smallerGap"):t("mission5.page2.largerGap")}</span></div></div><p className="l5-label">{t("mission5.labels.reviewed")}</p>{seen.size===2&&<Takeaway>{t("mission5.page2.takeaway")}</Takeaway>}<details className="l5-technical"><summary>{t("mission5.labels.technical")}</summary><p>{t("mission5.page2.technical")}</p></details><Bridge>{t("mission5.page2.bridge")}</Bridge></section>}

export function Lesson5Page3({active,t,onComplete}){const[adjusted,setAdjusted]=useState(false);function adjust(){setAdjusted(true);onComplete?.()}const values=adjusted?ADJUSTMENT.after:ADJUSTMENT.before;return <section hidden={!active} className="lesson-5-page"><Question icon={SlidersHorizontal} eyebrow={t("mission5.page3.eyebrow")}>{t("mission5.page3.question")}</Question><p className="l5-intro">{t("mission5.page3.intro")}</p><div className={`l5-dial-workshop ${adjusted?"is-adjusted":""}`}><div className="l5-dials">{values.map((value,index)=><span key={index}><i style={{"--turn":`${value*3}deg`}}/><strong>{value}</strong></span>)}</div><ArrowRight/><Probabilities items={["ball","cat","moon","sandwich"].map((token,index)=>({token,probability:values[index]}))}/><button className="primary" type="button" disabled={adjusted} onClick={adjust}><Gauge/>{adjusted?t("mission5.actions.adjusted"):t("mission5.actions.adjust")}</button><img src="/assets/img/mission-robot-pointing.png" alt="" aria-hidden="true"/></div><p className="l5-label">{t("mission5.labels.illustrative")}</p>{adjusted&&<Takeaway>{t("mission5.page3.takeaway")}</Takeaway>}<details className="l5-technical"><summary>{t("mission5.labels.technical")}</summary><p>{t("mission5.page3.technical")}</p></details><Bridge>{t("mission5.page3.bridge")}</Bridge></section>}

export function Lesson5Page4({active,t,onComplete}){const[processed,setProcessed]=useState(new Set());function process(id){setProcessed(current=>{const next=new Set(current).add(id);if(next.size>=2)onComplete?.();return next})}return <section hidden={!active} className="lesson-5-page"><Question icon={RefreshCcw} eyebrow={t("mission5.page4.eyebrow")}>{t("mission5.page4.question")}</Question><p className="l5-intro">{t("mission5.page4.intro")}</p><div className="l5-example-conveyor">{EXAMPLE_GROUPS.map(group=><article className={processed.has(group.id)?"is-processed":""} key={group.id}><Network/><strong>{t(`mission5.page4.groups.${group.id}`)}</strong>{group.examples.map(text=><p key={text}>{text}</p>)}<button type="button" onClick={()=>process(group.id)}>{processed.has(group.id)?t("mission5.actions.processed"):t("mission5.actions.process")}</button>{processed.has(group.id)&&<small>{t(`mission5.page4.results.${group.id}`)}</small>}</article>)}</div>{processed.has("money")&&<div className="l5-pattern-change"><div><small>{t("mission5.page4.before")}</small><Probabilities items={SAVINGS_BEFORE}/></div><ArrowRight/><div><small>{t("mission5.page4.after")}</small><Probabilities items={SAVINGS_AFTER}/></div></div>}<p className="l5-label">{t("mission5.labels.controlled")}</p>{processed.size>=2&&<Takeaway>{t("mission5.page4.takeaway")}</Takeaway>}<Bridge>{t("mission5.page4.bridge")}</Bridge></section>}

export function Lesson5Page5({active,t,onComplete}){const[answers,setAnswers]=useState({});function answer(key,value){const next={...answers,[key]:value};setAnswers(next);if(next.copy==="copy"&&next.pattern==="generalise")onComplete?.()}const done=answers.copy==="copy"&&answers.pattern==="generalise";return <section hidden={!active} className="lesson-5-page"><Question icon={Network} eyebrow={t("mission5.page5.eyebrow")}>{t("mission5.page5.question")}</Question><p className="l5-intro">{t("mission5.page5.intro")}</p><div className="l5-pattern-cards"><article><small>{t("mission5.page5.exact")}</small><p>{t("mission5.page5.trainingLabel")} “The puppy chased the ball.”</p><strong>{t("mission5.page5.outputLabel")} “The puppy chased the ball.”</strong><div><button type="button" aria-pressed={answers.copy==="copy"} onClick={()=>answer("copy","copy")}>{t("mission5.page5.copying")}</button><button type="button" aria-pressed={answers.copy==="generalise"} onClick={()=>answer("copy","generalise")}>{t("mission5.page5.generalising")}</button></div></article><article><small>{t("mission5.page5.new")}</small><p>{t("mission5.page5.trainingLabel")} “She saved money in the bank.”</p><strong>{t("mission5.page5.newLabel")} “He put his savings in the bank.”</strong><div><button type="button" aria-pressed={answers.pattern==="copy"} onClick={()=>answer("pattern","copy")}>{t("mission5.page5.copying")}</button><button type="button" aria-pressed={answers.pattern==="generalise"} onClick={()=>answer("pattern","generalise")}>{t("mission5.page5.generalising")}</button></div></article></div>{Object.keys(answers).length>0&&<div className="l5-feedback" aria-live="polite">{done?t("mission5.page5.correct"):t("mission5.page5.tryAgain")}</div>}{done&&<Takeaway>{t("mission5.page5.takeaway")}</Takeaway>}<div className="l5-caution"><Sparkles/><p>{t("mission5.page5.caution")}</p></div><Bridge>{t("mission5.page5.bridge")}</Bridge></section>}

export function Lesson5Page6({active,t,complete,onComplete}){const training=["text","predict","actual","error","adjust","repeat","patterns"];const course=["tokens","context","clues","selection","training"];return <section hidden={!active} className="lesson-5-page"><Question icon={Sparkles} eyebrow={t("mission5.page6.eyebrow")}>{t("mission5.page6.question")}</Question><p className="l5-intro">{t("mission5.page6.intro")}</p><div className="l5-loop-map">{training.map((key,index)=><React.Fragment key={key}><article><span>{index+1}</span><strong>{t(`mission5.page6.loop.${key}`)}</strong></article>{index<training.length-1&&<ArrowRight/>}</React.Fragment>)}</div><div className="l5-phase-map"><section><h3>{t("mission5.page6.generation")}</h3><p>{t("mission5.page6.generationFlow")}</p></section><section><h3>{t("mission5.page6.training")}</h3><p>{t("mission5.page6.trainingFlow")}</p></section></div><div className="l5-course-map"><h3>{t("mission5.page6.course")}</h3>{course.map((key,index)=><article key={key}><span>{index+1}</span><strong>{t(`mission5.page6.courseMap.${key}`)}</strong></article>)}</div><div className="l5-accuracy"><DoorOpen/><p>{t("mission5.page6.accuracy")}</p></div><Takeaway>{t("mission5.page6.takeaway")}</Takeaway><button className="primary l5-complete" type="button" disabled={!complete} onClick={onComplete}>{complete?t("mission5.actions.complete"):t("mission5.actions.incomplete")}</button></section>}
