import React, { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, BookOpenCheck, Check, Database, Eye, FileCheck2, Scale, Search, ShieldCheck, UserRound, Users } from "lucide-react";
import MissionLessonShell, { parseLessonPage } from "../mission1/MissionLessonShell.jsx";
import { useI18n } from "../i18n/index.jsx";
import { writeProgress } from "../state/progress.js";
import { MISSION_COPY, PAGED_MISSIONS } from "./missionCurriculumData.js";
import { PageTransitionBridge, PlayfulDiscoveryPanel, PlayfulWorkbench, TactileChoiceCard } from "./PlayfulMissionKit.jsx";
import "./pagedCurriculum.css";

const truthOptions = [
  ["The answer sounds smooth.", "plausible"], ["A reliable source confirms the claim.", "confirmed"],
  ["The answer uses confident words.", "plausible"], ["Two suitable sources agree.", "confirmed"]
];
const evidenceOptions = [
  ["A current museum page about the object", "strong"], ["An unrelated social post", "weak"], ["A source that names its evidence", "strong"]
];
const trainingPairs = [["bonjour", "greeting"], ["hello", "greeting"], ["goodbye", "farewell"]];
const causes = ["Unbalanced examples", "Historical stereotypes", "Missing groups", "Label choices"];

function progressUpdate(previous, missionId, progressValue, completed = false) {
  const next = structuredClone(previous);
  const current = next.missions[missionId] || { progress:0, completed:false };
  next.missions[missionId] = { progress:completed ? 100 : Math.max(current.progress || 0, progressValue), completed:current.completed || completed };
  writeProgress(next);
  return next;
}

function Discovery({ children }) { return <PlayfulDiscoveryPanel>{children}</PlayfulDiscoveryPanel>; }

function Mission3Page({ page, mark }) {
  const [choices, setChoices] = useState({});
  const [revealed, setRevealed] = useState(false);
  if (page === 1) return <Activity title="Sort the signs" prompt="Which signs only sound plausible, and which actually help confirm a claim?"><div className="pcm-choice-grid">{truthOptions.map(([text, kind]) => <button key={text} onClick={() => setChoices((v)=>({...v,[text]:kind}))} className={choices[text] ? `is-${kind}`:""}>{text}{choices[text] && <small>{kind === "confirmed" ? "helps confirm" : "does not prove it"}</small>}</button>)}</div>{Object.keys(choices).length === 4 && <Discovery>Fluent language is not the same as evidence that a statement is true.</Discovery>}</Activity>;
  if (page === 2) return <Activity title="Follow the answer trail" prompt="Reveal how a familiar wording pattern can lead to a confident mistake."><CauseChain steps={["Question: Can penguins fly?", "Pattern: birds often fly", "Answer: Yes, confidently", "Reality check: penguins cannot fly"]} onComplete={()=>{setRevealed(true);mark("mistake");}} />{revealed && <Discovery>The model did not decide to lie. A plausible language pattern produced an incorrect answer.</Discovery>}</Activity>;
  if (page === 3) return <Activity title="Open the evidence shelves" prompt="Inspect what a response may be missing or unable to use."><div className="pcm-shelves">{["Patterns from training", "New information", "Private information", "Missing details", "Outdated information"].map(x=><button key={x} aria-pressed={Boolean(choices[x])} onClick={()=>setChoices(v=>({...v,[x]:true}))}><BookOpenCheck />{x}{choices[x]&&<Check/>}</button>)}</div>{Object.keys(choices).length>=4&&<Discovery>A model cannot reliably use information that is unavailable, missing or out of date.</Discovery>}</Activity>;
  if (page === 4) return <Activity title="Which evidence helps?" prompt="Inspect each source before trusting the claim."><div className="pcm-choice-grid">{evidenceOptions.map(([text,kind])=><button key={text} onClick={()=>setChoices(v=>({...v,[text]:kind}))} className={choices[text]?`is-${kind}`:""}><Search/>{text}{choices[text]&&<small>{kind === "strong" ? "relevant evidence" : "weak evidence"}</small>}</button>)}</div>{Object.keys(choices).length===3&&<Discovery>Useful evidence should be relevant, suitable and current.</Discovery>}</Activity>;
  if (page === 5) return <Activity title="Detective case" prompt="A generated answer says: ‘Penguins can fly.’ What should you do?"><Choice options={["Accept it because it sounds clear","Check a suitable animal reference","Count how many words it uses"]} correct={1} onCorrect={()=>mark("detective")} discovery="A reliable animal source shows that penguins are flightless birds. Suitable evidence matters more than fluent wording." /></Activity>;
  if (page === 6) return <Activity title="Set the checking level" prompt="Choose a situation. Notice how the possible consequence changes the care needed."><div className="pcm-stakes">{[["Story idea","Explore freely"],["Homework fact","Check a suitable source"],["Money decision","Verify carefully with a trusted adult"],["Health or safety advice","Pause, verify and ask a trusted adult"]].map(([a,b])=><button key={a} onClick={()=>setChoices({[a]:b})}><strong>{a}</strong><span>{choices[a]||"Choose"}</span></button>)}</div>{Object.keys(choices).length>0&&<Discovery>The higher the possible harm, the more carefully a claim should be checked.</Discovery>}</Activity>;
  return <Summary chain={["Prompt","Pattern-based answer","May sound confident","Check important claims"]} points={["Smooth writing is not proof.","Models can lack suitable information.","People should verify important claims."]} />;
}

function Mission4Page({ page, mark }) {
  const [selected,setSelected]=useState([]); const [answer,setAnswer]=useState("");
  const toggle=x=>setSelected(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x]);
  if(page===1)return <Activity title="Explore the example crates" prompt="Training data can contain many kinds of examples."><div className="pcm-crates">{["Stories","Questions and answers","Web text","Labelled examples"].map(x=><button key={x} onClick={()=>toggle(x)} className={selected.includes(x)?"selected":""}><Database/>{x}</button>)}</div>{selected.length>=3&&<Discovery>Training data is the collection of examples used while model values are adjusted.</Discovery>}</Activity>;
  if(page===2)return <Activity title="Group the examples" prompt="Reveal repeated relationships, then follow what training changes."><div className="pcm-pairs">{trainingPairs.map(([a,b])=><button key={a} aria-pressed={selected.includes(a)} onClick={()=>toggle(a)} className={selected.includes(a)?"selected":""}><b>{a}</b><ArrowRight/><span>{selected.includes(a)?b:"?"}</span></button>)}</div>{selected.length===3&&<><div className="pcm-training-adjustment"><span>Many examples</span><ArrowRight/><span>Model values adjusted during training</span><ArrowRight/><span>Pattern becomes easier to predict</span></div><Discovery>Across many examples, training gradually adjusts numerical model values to make recurring patterns easier to predict.</Discovery></>}</Activity>;
  if(page===3)return <Activity title="Find the rule" prompt="hello → greeting, bonjour → greeting. What pattern fits hola?"><Choice options={["greeting","farewell","number"]} correct={0} onCorrect={()=>mark("pattern")} discovery="The repeated examples suggest that ‘hola’ belongs with greetings." /></Activity>;
  if(page===4)return <Activity title="Test a new example" prompt="Use the same pattern for ‘auf Wiedersehen’. Which label fits?"><Choice options={["greeting","farewell","question"]} correct={1} onCorrect={()=>mark("test")} discovery="A learned pattern can help with a similar new example, although it may not always be correct." /></Activity>;
  if(page===5)return <Activity title="Compare two data boxes" prompt="Choose the box more likely to support a useful pattern."><Choice options={["Accurate, varied and organised examples","The same incorrect example copied 100 times"]} correct={0} onCorrect={()=>setAnswer("good")} discovery="Quality and variety matter; repetition of poor data does not make it useful." /></Activity>;
  if(page===6)return <Activity title="Pack the useful examples" prompt="Choose relevant examples for learning greetings."><div className="pcm-choice-grid">{["hello → greeting","bonjour → greeting","a random weather number","hola → greeting"].map((x,i)=><button key={x} onClick={()=>{toggle(x);if(i!==2)mark("examples")}} className={selected.includes(x)?(i===2?"is-weak":"is-strong"):""}>{x}</button>)}</div>{selected.length>=2&&<Discovery>Relevant, accurate and varied examples are more helpful than simply adding anything.</Discovery>}</Activity>;
  if(page===7)return <Activity title="Keep the scale honest" prompt="Reveal what this classroom activity can and cannot show."><CauseChain steps={["Our cards: a tiny teaching example","Real training: vast data and computation","These clicks do not retrain Qwen or ChatGPT"]} onComplete={()=>setAnswer("limits")}/>{answer&&<Discovery>This activity illustrates an idea; it does not train a real large language model.</Discovery>}</Activity>;
  return <Summary chain={["Training examples","Adjusted model values","Learned patterns","Later predictions"]} points={["Models learn patterns from many examples.","Relevant, accurate and varied data matters.","Our classroom activity is not real LLM training."]}/>;
}

function Mission5Page({ page, mark, balance, setBalance }) {
  const [selected,setSelected]=useState([]); const male=balance; const female=10-balance;
  const toggle=x=>setSelected(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x]);
  if(page===1)return <Activity title="See who is represented" prompt="Open this tiny example set and notice who appears — and who appears less often."><div className="pcm-representation-scene"><div><FileCheck2/><span>Example 1</span></div><div><FileCheck2/><span>Example 2</span></div><div className="is-missing"><UserRound/><span>Whose example is missing?</span></div></div><button className="pcm-big-action" onClick={()=>setSelected(["seen"])}><Users/>Inspect the example set</button>{selected.length>0&&<Discovery>Representation means which people, situations and viewpoints appear in a dataset. Counts are one clue, not the whole fairness story.</Discovery>}</Activity>;
  if(page===2)return <Activity title="Count the representation" prompt="This simplified teaching dataset contains ten doctor examples."><PeopleBoard male={9} female={1}/><Choice options={["Men appear in 9 of 10 examples","The groups appear equally often","Women appear in 9 of 10 examples"]} correct={0} onCorrect={()=>mark("inspect")} discovery="Men appear much more often in this tiny example set: 9 out of 10 examples." /></Activity>;
  if(page===3)return <Activity title="Change the example balance" prompt="Move the slider. Watch the example cards move between the two trays."><PeopleBoard male={male} female={female}/><input aria-label="Number of examples showing men" aria-valuetext={`Men shown in ${male} of 10 examples; women shown in ${female} of 10 examples`} type="range" min="0" max="10" value={balance} onChange={e=>{setBalance(Number(e.target.value));mark("balance")}}/><p className="pcm-live">Men shown {male}/10 · Women shown {female}/10</p><Discovery>The composition changes immediately. Equal counts can improve representation in this tiny example, but equal counts alone do not prove a real system is fair.</Discovery></Activity>;
  if(page===4)return <Activity title="Connect data to an output tendency" prompt="This reviewed demonstration mirrors the current example balance; it is not a real model prediction."><div className="pcm-output"><PeopleBoard male={male} female={female}/><ArrowRight/><div><strong>Teaching tendency</strong><span style={{"--amount":`${male*10}%`}}>Male examples {male*10}%</span><span style={{"--amount":`${female*10}%`}}>Female examples {female*10}%</span></div></div><p className="pcm-boundary">Simplified teaching demonstration — not live model output.</p><button className="primary" onClick={()=>mark("output")}>I followed the change</button></Activity>;
  if(page===5)return <Activity title="Find the missing perspectives" prompt="Open each faded space to see what the dataset might leave out."><div className="pcm-missing-perspectives">{causes.map(x=><button key={x} onClick={()=>toggle(x)} className={selected.includes(x)?"selected":""}><AlertTriangle/>{selected.includes(x)?x:"Missing example"}</button>)}</div>{selected.length===4&&<Discovery>Absence matters too. Missing groups, situations and viewpoints can shape which patterns are learned.</Discovery>}</Activity>;
  if(page===6)return <Activity title="Who may be affected?" prompt="Inspect each person-and-consequence card before deciding how carefully to test."><div className="pcm-impact-cards">{[["Student","May see fewer suitable clubs"],["Teacher","May trust a narrow recommendation"],["School team","May repeat an unfair pattern"]].map(([person,effect])=><button key={person} onClick={()=>toggle(person)} className={selected.includes(person)?"selected":""}><UserRound/><strong>{person}</strong><span>{selected.includes(person)?effect:"Reveal possible effect"}</span></button>)}</div>{selected.length===3&&<Discovery>A system can affect different people in different ways. Responsible checking asks who could be helped, overlooked or harmed.</Discovery>}</Activity>;
  if(page===7)return <Activity title="Complete the inspection board" prompt="A club tool suggests robotics mostly to boys and art mostly to girls. Complete every responsible check."><div className="pcm-checklist">{["Inspect the data","Compare outputs","Consider affected groups","Decide whether this system is appropriate"].map(x=><button key={x} onClick={()=>{toggle(x);if(!selected.includes(x)&&selected.length>=2)mark("scenario")}} aria-pressed={selected.includes(x)}>{selected.includes(x)?<Check/>:<Eye/>}{x}</button>)}</div>{selected.length>=3&&<Discovery>Responsible checking combines evidence about data, outputs, affected people and the setting where a system is used.</Discovery>}</Activity>;
  return <Summary chain={["Patterns in data","May affect outputs","Inspect and test","Consider people affected"]} points={["Bias may come from imbalance, stereotypes or missing perspectives.","A teaching demo is not a real model result.","Responsible checking needs people and evidence."]}/>;
}

function Activity({title,prompt,children}) { const lower=title.toLowerCase(); const isTraining=/training|example|pattern|data box|classroom|rule|greeting|useful|scale honest/.test(lower); const isBias=/bias|balance|representation|checking|club|cause|missing perspective|affected|inspection/.test(lower); const variant=isTraining?"green":isBias?"orange":"purple"; const SceneIcon=isTraining?Database:isBias?Scale:Search; const robotSrc=isTraining?"/assets/img/mission5-robot-training.png":isBias?"/assets/img/mission-robot-pointing.png":"/assets/img/mission3-robot-hallucination.png"; return <PlayfulWorkbench variant={variant} label={title} instruction={prompt} robotSrc={robotSrc} icon={SceneIcon}><section className="pcm-activity">{children}</section></PlayfulWorkbench>; }
function Choice({options,correct,onCorrect,discovery}){const [picked,setPicked]=useState(null);const right=picked===correct;return <><div className="pcm-choice-grid" role="radiogroup">{options.map((x,i)=><TactileChoiceCard role="radio" aria-checked={picked===i} selected={picked===i} tone={i===correct?"green":"blue"} key={x} className={picked===i?(right?"is-strong":"is-weak"):""} onClick={()=>{setPicked(i);if(i===correct)onCorrect?.()}}>{x}{picked===i&&<small>{right?"Good evidence":"Look again"}</small>}</TactileChoiceCard>)}</div>{right&&<Discovery>{discovery}</Discovery>}</>}
function CauseChain({steps,onComplete}){const [shown,setShown]=useState(1);useEffect(()=>{if(shown===steps.length)onComplete?.()},[shown,steps.length]);return <div className="pcm-chain">{steps.map((x,i)=><React.Fragment key={x}><button disabled={i>shown} className={i<shown?"shown":""} onClick={()=>setShown(v=>Math.min(steps.length,v+1))}>{i<shown?<Check/>:i+1}<span>{i<shown?x:"Reveal next step"}</span></button>{i<steps.length-1&&<ArrowRight/>}</React.Fragment>)}</div>}
function PeopleBoard({male,female}){return <div className="pcm-people" aria-label={`Teaching dataset: ${male} examples showing men and ${female} showing women`}><div><strong>Men shown <small>{male}/10</small></strong>{Array.from({length:male},(_,i)=><span className="pcm-person-card" key={`m${i}`} aria-label={`Example showing a man ${i+1}`}><UserRound aria-hidden="true"/></span>)}</div><div><strong>Women shown <small>{female}/10</small></strong>{Array.from({length:female},(_,i)=><span className="pcm-person-card" key={`f${i}`} aria-label={`Example showing a woman ${i+1}`}><UserRound aria-hidden="true"/></span>)}</div></div>}
function Summary({chain,points}){const title=chain[0].includes("Training")?"Put the training journey together":chain[0].includes("Patterns in data")?"Put the responsible checking journey together":"Put the investigation together";return <Activity title={title} prompt="Follow the full causal chain, then explain it in your own words."><div className="pcm-summary-chain">{chain.map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<chain.length-1&&<ArrowRight/>}</React.Fragment>)}</div><div className="pcm-discovery-cards">{points.map(x=><article key={x}><ShieldCheck/><p>{x}</p></article>)}</div></Activity>}

export default function PagedCurriculumMission({ missionId, progress, setProgress, navigate, notify }) {
  const {language}=useI18n(); const copy=MISSION_COPY[language]||MISSION_COPY.en; const mission=PAGED_MISSIONS[missionId]; const pages=mission.pages;
  const [currentPage,setCurrentPage]=useState(()=>parseLessonPage(window.location.search,pages.length));
  const [visited,setVisited]=useState(()=>new Set([parseLessonPage(window.location.search,pages.length)])); const [continued,setContinued]=useState(new Set());
  const [activities,setActivities]=useState(new Set()); const [balance,setBalance]=useState(9);
  useEffect(()=>{const pop=()=>{const page=parseLessonPage(window.location.search,pages.length);setCurrentPage(page);setVisited(v=>new Set(v).add(page))};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop)},[pages.length]);
  function changePage(page){const safe=Math.min(pages.length,Math.max(1,page));const url=new URL(window.location.href);url.searchParams.set("page",String(safe));window.history.pushState({},"",`${url.pathname}${url.search}`);setCurrentPage(safe);setVisited(v=>new Set(v).add(safe));}
  function mark(key){setActivities(v=>new Set(v).add(key));}
  const requirements=missionId===3?["detective","mistake"]:missionId===5?["examples","pattern","test"]:["inspect","balance","output","scenario"];
  const completeReady=requirements.every(x=>activities.has(x))&&visited.has(pages.length);
  function complete(){if(!completeReady){notify?.("Complete the key activities before finishing this Mission.");return}setProgress(previous=>progressUpdate(previous,missionId,100,true));notify?.(`Mission ${mission.order} complete.`);navigate("/missions")}
  const recommended=pages.findIndex((_,i)=>!visited.has(i+1))+1; const page=pages[currentPage-1];
  const labels={backToMissions:copy.backMissions,missionCount:`Mission ${mission.order} of 5`,topicLabel:mission.topic,pageCount:`${copy.page} ${currentPage} / ${pages.length}`,back:copy.back,next:copy.next,prototypeEndAction:completeReady?copy.complete:"Activities incomplete",prototypeLabel:currentPage===pages.length?`${activities.size} discoveries saved`:mission.topic,robotAlt:"AI Explorer learning robot"};
  const recommendation={visible:recommended>0&&currentPage>recommended&&!continued.has(currentPage),message:"You can explore this page now. The earlier pages explain the ideas used here.",goLabel:"Go to recommended page",continueLabel:"Continue here",onGoRecommended:()=>changePage(recommended),onContinue:()=>setContinued(v=>new Set(v).add(currentPage))};
  const content=missionId===3?<Mission3Page page={currentPage} mark={mark}/>:missionId===5?<Mission4Page page={currentPage} mark={mark}/>:<Mission5Page page={currentPage} mark={mark} balance={balance} setBalance={setBalance}/>;
  const nextPage=pages[currentPage];
  const missionEndBridge=missionId===3?"Next, explore how the patterns behind answers were learned during training.":missionId===5?"Next, inspect how learned patterns can reflect imbalance or missing perspectives.":"You are ready to connect representation, output patterns and responsible checking.";
  return <MissionLessonShell currentPage={currentPage} pageCount={pages.length} onPageChange={changePage} onBackToMissions={()=>navigate("/missions")} title={page[1]} subtitle={page[2]} labels={labels} recommendation={recommendation} rootClassName={`paged-curriculum-mission paged-mission-playful pcm-${mission.order} pcm-page-${page[0]} playful-learning-scope`} robotImage={mission.robot}>{content}<PageTransitionBridge label={copy.bridge}>{nextPage?nextPage[2]:missionEndBridge}</PageTransitionBridge>{currentPage===pages.length&&<div className="pcm-finish"><p>{completeReady?"All required discoveries are complete.":"Explore the key activities before completing this Mission."}</p><button className="primary" disabled={!completeReady} onClick={complete}>{copy.complete}</button></div>}</MissionLessonShell>;
}
