import React,{useCallback,useEffect,useState} from "react";
import MissionLessonShell,{parseLessonPage} from "../mission1/MissionLessonShell.jsx";
import {useI18n} from "../i18n/index.jsx";
import {writeProgress} from "../state/progress.js";
import LessonPageHero from "../pagedMissions/LessonPageHero.jsx";
import {Lesson4NewPage1,Lesson4ScorePage,Lesson4NewPage2,Lesson4NewPage3,Lesson4NewPage4} from "./Lesson4TeachingPages.jsx";
import {Lesson4Page6} from "./Lesson4Pages.jsx";
import "./lesson4Paged.css";
import "./lesson4Live.css";

export const LESSON_4_PAGES=Object.freeze([["predict","mission4.page1.title","mission4.page1.subtitle"],["scores","mission4.scorePage.title","mission4.scorePage.subtitle"],["probabilities","mission4.probabilityPage.title","mission4.probabilityPage.subtitle"],["live","mission4.page3.title","mission4.page3.subtitle"],["check","mission4.page4.title","mission4.page4.subtitle"],["summary","mission4.page6.title","mission4.page6.subtitle"]]);
const ROBOTS=["missions-robot-target.png","missions-robot-target.png","mission5-robot-training.png","mission-robot-pointing.png","mission5-robot-training.png","missions-robot-target.png"];
const REQUIRED=["scores","probabilities","live","quiz"];
export default function Lesson4Paged({setProgress,navigate,notify}){const{t}=useI18n();const pageCount=LESSON_4_PAGES.length;const initial=parseLessonPage(window.location.search,pageCount);const[currentPage,setCurrentPage]=useState(initial);const[visited,setVisited]=useState(()=>new Set([initial]));const[continued,setContinued]=useState(()=>new Set());const[activities,setActivities]=useState(()=>new Set());const mark=useCallback(key=>setActivities(current=>new Set(current).add(key)),[]);
useEffect(()=>{const pop=()=>{const page=parseLessonPage(window.location.search,pageCount);setCurrentPage(page);setVisited(current=>new Set(current).add(page))};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop)},[pageCount]);
function changePage(next){const safe=Math.min(pageCount,Math.max(1,next));const url=new URL(window.location.href);url.searchParams.set("page",String(safe));window.history.pushState({},"",`${url.pathname}${url.search}`);setCurrentPage(safe);setVisited(current=>new Set(current).add(safe))}
const recommended=LESSON_4_PAGES.findIndex((_,index)=>!visited.has(index+1))+1;const recommendation={visible:recommended>0&&currentPage>recommended&&!continued.has(currentPage),message:t("learningMode.notice"),goLabel:t("learningMode.goRecommended"),continueLabel:t("learningMode.continueHere"),onGoRecommended:()=>changePage(recommended),onContinue:()=>setContinued(current=>new Set(current).add(currentPage))};const page=LESSON_4_PAGES[currentPage-1];const complete=REQUIRED.every(key=>activities.has(key))&&visited.has(pageCount);const labels={backToMissions:t("mission4.shell.backToLearn"),missionCount:t("mission4.shell.lessonCount"),topicLabel:t("mission4.shell.topic"),pageCount:t("mission4.shell.pageCount",{current:currentPage,total:pageCount}),back:t("mission4.shell.back"),next:t("mission4.shell.next"),prototypeEndAction:t("mission4.shell.incomplete"),prototypeLabel:t("mission4.shell.topic"),navigationLabel:t("common.lesson.navigationLabel"),robotAlt:t("mission4.shell.robotAlt")};
function continueToNextLesson(){if(complete){setProgress(previous=>{const next=structuredClone(previous);next.missions[5]={progress:100,completed:true};writeProgress(next);return next});notify?.(t("mission4.actions.completedNotice"))}navigate("/mission/5-bias-paged")}
return <MissionLessonShell currentPage={currentPage} pageCount={pageCount} onPageChange={changePage} onEnd={continueToNextLesson} onBackToMissions={()=>navigate("/missions")} title={t(page[1])} subtitle={t(page[2])} labels={{...labels,prototypeEndAction:t("mission4.shell.nextLesson")}} recommendation={recommendation} hideNext={currentPage===5} skipAction={currentPage===5?{label:t("mission4.skipQuiz"),onClick:()=>changePage(6)}:null} rootClassName={`lesson-4-paged l4-new-root l4-page-${page[0]} paged-mission-playful playful-learning-scope ${currentPage===5?"mission-2-paged lesson-quiz-layout":""}`} robotImage={currentPage<=3||currentPage===5?null:`/assets/img/${ROBOTS[currentPage-1]}`} pageHero={<LessonPageHero lessonIndex={4} lessonCount={5} lessonProgressLabel={t("common.lesson.progress",{current:4,total:5})} lessonName={t("mission4.shell.topic")} title={t(page[1])} subtitle={t(page[2])} illustration={`/assets/img/${ROBOTS[currentPage-1]}`} illustrationAlt={labels.robotAlt} headingId={`lesson-4-page-${currentPage}-title`}/>}><Lesson4NewPage1 active={currentPage===1} t={t}/><Lesson4ScorePage active={currentPage===2} t={t} onComplete={()=>mark("scores")}/><Lesson4NewPage2 active={currentPage===3} t={t} onComplete={()=>mark("probabilities")}/><Lesson4NewPage3 active={currentPage===4} t={t} onComplete={()=>mark("live")}/><Lesson4NewPage4 active={currentPage===5} t={t} onComplete={()=>mark("quiz")} onContinue={()=>changePage(6)}/><Lesson4Page6 active={currentPage===6} t={t} complete={complete} onContinue={continueToNextLesson}/></MissionLessonShell>}
