import React,{useCallback,useEffect,useState} from "react";
import MissionLessonShell,{parseLessonPage} from "../mission1/MissionLessonShell.jsx";
import {useI18n} from "../i18n/index.jsx";
import {writeProgress} from "../state/progress.js";
import {Lesson4NewPage1,Lesson4NewPage2,Lesson4NewPage3,Lesson4NewPage4} from "./Lesson4TeachingPages.jsx";
import "./lesson4Paged.css";
import "./lesson4Live.css";

export const LESSON_4_PAGES=Object.freeze([["predict","mission4.page1.title","mission4.page1.subtitle"],["choose","mission4.page2.title","mission4.page2.subtitle"],["live","mission4.page3.title","mission4.page3.subtitle"],["check","mission4.page4.title","mission4.page4.subtitle"]]);
const ROBOTS=["missions-robot-target.png","mission5-robot-training.png","mission-robot-pointing.png","mission5-robot-training.png"];
const REQUIRED=["probabilities","selection","live","quiz"];
export default function Lesson4Paged({setProgress,navigate,notify}){const{t}=useI18n();const pageCount=LESSON_4_PAGES.length;const initial=parseLessonPage(window.location.search,pageCount);const[currentPage,setCurrentPage]=useState(initial);const[visited,setVisited]=useState(()=>new Set([initial]));const[continued,setContinued]=useState(()=>new Set());const[activities,setActivities]=useState(()=>new Set());const mark=useCallback(key=>setActivities(current=>new Set(current).add(key)),[]);
useEffect(()=>{const pop=()=>{const page=parseLessonPage(window.location.search,pageCount);setCurrentPage(page);setVisited(current=>new Set(current).add(page))};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop)},[pageCount]);
function changePage(next){const safe=Math.min(pageCount,Math.max(1,next));const url=new URL(window.location.href);url.searchParams.set("page",String(safe));window.history.pushState({},"",`${url.pathname}${url.search}`);setCurrentPage(safe);setVisited(current=>new Set(current).add(safe));window.scrollTo({top:0,behavior:"smooth"})}
const recommended=LESSON_4_PAGES.findIndex((_,index)=>!visited.has(index+1))+1;const recommendation={visible:recommended>0&&currentPage>recommended&&!continued.has(currentPage),message:t("learningMode.notice"),goLabel:t("learningMode.goRecommended"),continueLabel:t("learningMode.continueHere"),onGoRecommended:()=>changePage(recommended),onContinue:()=>setContinued(current=>new Set(current).add(currentPage))};const page=LESSON_4_PAGES[currentPage-1];const complete=REQUIRED.every(key=>activities.has(key))&&visited.has(pageCount);const labels={backToMissions:t("mission4.shell.backToLearn"),missionCount:t("mission4.shell.lessonCount"),topicLabel:t("mission4.shell.topic"),pageCount:t("mission4.shell.pageCount",{current:currentPage,total:pageCount}),back:t("mission4.shell.back"),next:t("mission4.shell.next"),prototypeEndAction:t("mission4.shell.incomplete"),prototypeLabel:t("mission4.shell.topic"),robotAlt:t("mission4.shell.robotAlt")};
function continueToNextLesson(){if(complete){setProgress(previous=>{const next=structuredClone(previous);next.missions[5]={progress:100,completed:true};writeProgress(next);return next});notify?.(t("mission4.actions.completedNotice"))}navigate("/mission/5-bias-paged")}
return <MissionLessonShell currentPage={currentPage} pageCount={pageCount} onPageChange={changePage} onEnd={continueToNextLesson} onBackToMissions={()=>navigate("/missions")} title={t(page[1])} subtitle={t(page[2])} labels={{...labels,prototypeEndAction:t("mission4.shell.nextLesson")}} recommendation={recommendation} rootClassName={`lesson-4-paged l4-new-root l4-page-${page[0]} paged-mission-playful playful-learning-scope`} robotImage={`/assets/img/${ROBOTS[currentPage-1]}`}><Lesson4NewPage1 active={currentPage===1} t={t} onComplete={()=>mark("probabilities")}/><Lesson4NewPage2 active={currentPage===2} t={t} onComplete={()=>mark("selection")}/><Lesson4NewPage3 active={currentPage===3} t={t} onComplete={()=>mark("live")}/><Lesson4NewPage4 active={currentPage===4} t={t} onComplete={()=>mark("quiz")}/></MissionLessonShell>}
