import React, { useState } from "react";
import { ArrowRight, BarChart3, Check, ChevronRight, CircleDot, DoorOpen, Gauge, GitCompareArrows, LockKeyhole, Play, Plus, RefreshCcw, RotateCcw, Sparkles, Target, Undo2 } from "lucide-react";
import { CAT_CANDIDATES, CAT_PROMPT, REVIEWED_SAMPLING_SEQUENCE, REVIEWED_STORIES } from "./lesson4TeachingData.js";
import LessonSummaryPage from "../pagedMissions/LessonSummaryPage.jsx";

function Question({number,eyebrow,children=null}){return <header className="l4-question"><span aria-hidden="true">{number}</span><div><small>{eyebrow}</small>{children&&<h2>{children}</h2>}</div></header>}
function Takeaway({children}){return <div className="l4-takeaway" role="status"><span><Check/></span><p>{children}</p></div>}
function Bridge({children}){return <div className="l4-bridge"><span><ChevronRight/></span><p>{children}</p></div>}
function PromptStrip({extra=[],slot=true}){return <div className="l4-prompt-strip"><span>{CAT_PROMPT}</span>{extra.map((token,index)=><b key={`${token}-${index}`}>{token}</b>)}{slot&&<em>next?</em>}</div>}
function Candidate({item,selected,onClick,showProbability=false}){return <button type="button" aria-pressed={selected} className={`l4-candidate tone-${item.tone||"blue"} ${selected?"is-selected":""}`} onClick={onClick}><span>{item.token}</span>{showProbability&&<><div className="l4-score-ribbon"><i style={{"--score":`${item.probability}%`}}/></div><strong>{item.probability}%</strong></>}{selected&&<Check aria-hidden="true"/>}</button>}

export function Lesson4Page1({active,t}){
  const [selected,setSelected]=useState([]);const discovered=selected.length>=2;
  const pick=token=>setSelected(current=>current.includes(token)?current.filter(item=>item!==token):[...current,token]);
  return <section hidden={!active} className="lesson-4-page l4-page-one"><Question number="1" eyebrow={t("mission4.page1.eyebrow")}>{t("mission4.page1.question")}</Question><p className="l4-intro">{t("mission4.page1.intro")}</p><div className="l4-launch-scene"><div className="l4-context-flow"><PromptStrip/><ArrowRight/><span>{t("mission4.page1.possible")}</span></div><div className="l4-launch-pads" role="group" aria-label={t("mission4.page1.action")}>{CAT_CANDIDATES.map(item=><Candidate item={item} selected={selected.includes(item.token)} onClick={()=>pick(item.token)} key={item.token}/>)}</div><img src="/assets/img/missions-robot-target.png" alt="" aria-hidden="true"/><p className="l4-machine-label">{t("mission4.page1.analogy")}</p></div><p className="l4-action-hint">{t("mission4.page1.action")}</p>{discovered&&<><div className="l4-feedback" aria-live="polite"><Sparkles/>{t("mission4.page1.feedback")}</div><Takeaway>{t("mission4.page1.takeaway")}</Takeaway></>}<Bridge>{t("mission4.page1.bridge")}</Bridge></section>
}

export function Lesson4Page2({active,t,onComplete}){
  const [revealed,setRevealed]=useState(false);const [picked,setPicked]=useState("");
  function reveal(){setRevealed(true);onComplete?.()}
  return <section hidden={!active} className="lesson-4-page l4-page-two"><Question number="2" eyebrow={t("mission4.page2.eyebrow")}>{t("mission4.page2.question")}</Question><p className="l4-intro">{t("mission4.page2.intro")}</p><div className={`l4-score-console ${revealed?"is-revealed":""}`}><PromptStrip/><div className="l4-score-tracks">{CAT_CANDIDATES.map(item=><Candidate item={item} selected={picked===item.token} onClick={()=>revealed&&setPicked(item.token)} showProbability={revealed} key={item.token}/>)}</div><button type="button" className="primary l4-show-scores" disabled={revealed} onClick={reveal}><Gauge/>{revealed?t("mission4.actions.scoresShown"):t("mission4.actions.showScores")}</button><img src="/assets/img/mission5-robot-training.png" alt="" aria-hidden="true"/><span className="l4-data-label">{t("mission4.labels.reviewedProbabilities")}</span></div>{revealed&&<><p className="l4-action-hint">{t("mission4.page2.action")}</p>{picked&&<div className="l4-feedback" aria-live="polite">{picked==="mat"?t("mission4.page2.highest"):t("mission4.page2.compareAgain")}</div>}<Takeaway>{t("mission4.page2.takeaway")}</Takeaway></>}<details className="l4-technical"><summary>{t("mission4.labels.technicalNote")}</summary><p>{t("mission4.page2.technical")}</p></details><Bridge>{t("mission4.page2.bridge")}</Bridge></section>
}

export function Lesson4Page3({active,t,onComplete}){
  const [mode,setMode]=useState("highest");const [ranModes,setRanModes]=useState(()=>new Set());const [sampleIndex,setSampleIndex]=useState(0);const [result,setResult]=useState("");
  function chooseMode(next){setMode(next);setResult("")}
  function run(){if(mode==="highest")setResult("mat");else{setResult(REVIEWED_SAMPLING_SEQUENCE[sampleIndex%REVIEWED_SAMPLING_SEQUENCE.length]);setSampleIndex(index=>index+1)}setRanModes(current=>{const updated=new Set(current).add(mode);if(updated.size===2)onComplete?.();return updated})}
  return <section hidden={!active} className="lesson-4-page l4-page-three"><Question number="3" eyebrow={t("mission4.page3.eyebrow")}>{t("mission4.page3.question")}</Question><p className="l4-intro">{t("mission4.page3.intro")}</p><div className="l4-mode-switch" role="group" aria-label={t("mission4.page3.modeLabel")}><button type="button" aria-pressed={mode==="highest"} onClick={()=>chooseMode("highest")}><Target/><strong>{t("mission4.page3.highestMode")}</strong><small>{t("mission4.page3.greedy")}</small></button><button type="button" aria-pressed={mode==="sampling"} onClick={()=>chooseMode("sampling")}><CircleDot/><strong>{t("mission4.page3.chanceMode")}</strong><small>{t("mission4.page3.sampling")}</small></button></div><div className={`l4-selector-machine is-${mode}`}><div className="l4-selector-candidates">{CAT_CANDIDATES.map(item=><span style={{"--share":item.probability}} key={item.token}><b>{item.token}</b><small>{item.probability}%</small></span>)}</div><div className="l4-selection-gate"><LockKeyhole/><small>{mode==="highest"?t("mission4.page3.highestRule"):t("mission4.page3.chanceRule")}</small><strong>{result||"?"}</strong></div><button type="button" className="primary" onClick={run}><Play/>{t("mission4.actions.runSelector")}</button><img src="/assets/img/mission-robot-pointing.png" alt="" aria-hidden="true"/><span className="l4-data-label">{t("mission4.labels.classroomSelection")}</span></div>{result&&<div className="l4-feedback" aria-live="polite">{mode==="highest"?t("mission4.page3.highestResult",{token:result}):t("mission4.page3.sampleResult",{token:result})}</div>}<Takeaway>{t("mission4.page3.takeaway")}</Takeaway><p className="l4-boundary">{t("mission4.page3.boundary")}</p><Bridge>{t("mission4.page3.bridge")}</Bridge></section>
}

export function Lesson4Page4({active,t,onComplete}){
  const [added,setAdded]=useState(false);function add(){setAdded(true);onComplete?.()}
  return <section hidden={!active} className="lesson-4-page l4-page-four"><Question number="4" eyebrow={t("mission4.page4.eyebrow")}>{t("mission4.page4.question")}</Question><p className="l4-intro">{t("mission4.page4.intro")}</p><div className={`l4-placement-scene ${added?"is-added":""}`}><div className="l4-before"><small>{t("mission4.page4.before")}</small><PromptStrip slot={!added} extra={added?["mat"]:[]}/></div><div className="l4-carried-token"><span>mat</span><ArrowRight/></div><button type="button" className="primary" disabled={added} onClick={add}><Plus/>{added?t("mission4.actions.tokenAdded"):t("mission4.actions.addToken")}</button><img src="/assets/img/mission-robot-pointing.png" alt="" aria-hidden="true"/>{added&&<div className="l4-new-slot"><span>{t("mission4.page4.updatedContext")}</span><em>next?</em></div>}</div>{added&&<><div className="l4-before-after"><span><small>{t("mission4.page4.before")}</small>{CAT_PROMPT}</span><b>+</b><span><small>{t("mission4.page4.selected")}</small>mat</span><ArrowRight/><span><small>{t("mission4.page4.after")}</small>{CAT_PROMPT} mat</span></div><Takeaway>{t("mission4.page4.takeaway")}</Takeaway></>}<Bridge>{t("mission4.page4.bridge")}</Bridge></section>
}

export function Lesson4Page5({active,t,onComplete}){
  const [storyIndex,setStoryIndex]=useState(0);const [tokens,setTokens]=useState([]);const [pending,setPending]=useState("");const story=REVIEWED_STORIES[storyIndex];const candidates=story.sets[Math.min(tokens.length,story.sets.length-1)];const finished=tokens.length===5;
  function place(){if(!pending||finished)return;const next=[...tokens,pending];setTokens(next);setPending("");if(next.length>=2)onComplete?.()}
  function teachingChoice(){const highest=candidates.reduce((best,item)=>item.probability>best.probability?item:best,candidates[0]);setPending(highest.token)}
  function restart(){setTokens([]);setPending("")}
  function another(){setStoryIndex(index=>(index+1)%REVIEWED_STORIES.length);restart()}
  return <section hidden={!active} className="lesson-4-page l4-page-five"><Question number="5" eyebrow={t("mission4.page5.eyebrow")}>{t("mission4.page5.question")}</Question><p className="l4-intro">{t("mission4.page5.intro")}</p><div className="l4-story-machine"><div className="l4-story-top"><span>{t("mission4.page5.reviewedStarter")}</span><strong>{t("mission4.page5.step",{current:tokens.length,total:5})}</strong></div><div className="l4-growing-story" aria-live="polite"><span>{story.starter}</span>{tokens.map((token,index)=><b key={`${token}-${index}`}>{token}</b>)}{!finished&&<em>next?</em>}</div><div className="l4-waiting-tray"><small>{t("mission4.page5.candidates")}</small>{candidates.map(item=><button type="button" aria-pressed={pending===item.token} className={pending===item.token?"is-selected":""} onClick={()=>setPending(item.token)} key={item.token}><span>{item.token}</span><i><b style={{"--score":`${item.probability}%`}}/></i><strong>{item.probability}%</strong></button>)}</div><div className="l4-story-actions"><button type="button" className="primary" disabled={!pending||finished} onClick={place}><Plus/>{t("mission4.actions.placeSelected")}</button><button type="button" className="outline" disabled={finished} onClick={teachingChoice}><Sparkles/>{t("mission4.actions.teachingChoose")}</button><button type="button" className="outline" disabled={!tokens.length} onClick={()=>{setTokens(current=>current.slice(0,-1));setPending("")}}><Undo2/>{t("mission4.actions.undo")}</button><button type="button" className="outline" onClick={restart}><RotateCcw/>{t("mission4.actions.restart")}</button><button type="button" className="outline" onClick={another}>{t("mission4.actions.anotherStarter")}</button></div><img src="/assets/img/mission5-robot-training.png" alt="" aria-hidden="true"/><span className="l4-data-label">{t("mission4.labels.teachingSimulation")}</span></div>{tokens.length>=2&&<><div className="l4-feedback"><RefreshCcw/>{t("mission4.page5.discovery")}</div><Takeaway>{t("mission4.page5.takeaway")}</Takeaway></>}<p className="l4-boundary">{t("mission4.page5.boundary")}</p><Bridge>{t("mission4.page5.bridge")}</Bridge></section>
}

export function Lesson4Page6({active,t,complete,onContinue}){
  const ideas=[
    {Icon:Gauge,title:t("mission4.page6.idea1Title"),copy:t("mission4.page6.idea1Copy")},
    {Icon:BarChart3,title:t("mission4.page6.idea2Title"),copy:t("mission4.page6.idea2Copy")},
    {Icon:CircleDot,title:t("mission4.page6.idea3Title"),copy:t("mission4.page6.idea3Copy")},
    {Icon:Target,title:t("mission4.page6.idea4Title"),copy:t("mission4.page6.idea4Copy")}
  ];
  return <LessonSummaryPage active={active} pageNumber="6" kicker={t("mission4.page6.eyebrow")} ideas={ideas} recap={t("mission4.page6.recap")} nuance={t("mission4.page6.nuance")} nextLabel={t("mission4.page6.nextLabel")} nextTitle={t("mission4.page6.nextTitle")} nextCopy={t("mission4.page6.next")} advisory={!complete?t("learningMode.notice"):""}/>
}
