import React,{useCallback,useEffect,useState} from "react";
import MissionLessonShell,{parseLessonPage} from "../mission1/MissionLessonShell.jsx";
import {useI18n} from "../i18n/index.jsx";
import {writeProgress} from "../state/progress.js";
import {Lesson4Page1,Lesson4Page2,Lesson4Page3,Lesson4Page4,Lesson4Page5,Lesson4Page6} from "./Lesson4Pages.jsx";
import "./lesson4Paged.css";

export const LESSON_4_PAGES=Object.freeze([["candidates","mission4.page1.title","mission4.page1.subtitle"],["scores","mission4.page2.title","mission4.page2.subtitle"],["choose","mission4.page3.title","mission4.page3.subtitle"],["add","mission4.page4.title","mission4.page4.subtitle"],["repeat","mission4.page5.title","mission4.page5.subtitle"],["summary","mission4.page6.title","mission4.page6.subtitle"]]);
const ROBOTS=["missions-robot-target.png","mission5-robot-training.png","mission-robot-pointing.png","mission-robot-pointing.png","mission5-robot-training.png","mission-robot-reading.png"];
const REQUIRED=["scores","modes","placed","cycles"];
export default function Lesson4Paged({setProgress,navigate,notify}){const{t}=useI18n();const initial=parseLessonPage(window.location.search,6);const[currentPage,setCurrentPage]=useState(initial);const[visited,setVisited]=useState(()=>new Set([initial]));const[continued,setContinued]=useState(()=>new Set());const[activities,setActivities]=useState(()=>new Set());const mark=useCallback(key=>setActivities(current=>new Set(current).add(key)),[]);
useEffect(()=>{const pop=()=>{const page=parseLessonPage(window.location.search,6);setCurrentPage(page);setVisited(current=>new Set(current).add(page))};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop)},[]);
function changePage(next){const safe=Math.min(6,Math.max(1,next));const url=new URL(window.location.href);url.searchParams.set("page",String(safe));window.history.pushState({},"",`${url.pathname}${url.search}`);setCurrentPage(safe);setVisited(current=>new Set(current).add(safe));window.scrollTo({top:0,behavior:"smooth"})}
const recommended=LESSON_4_PAGES.findIndex((_,index)=>!visited.has(index+1))+1;const recommendation={visible:recommended>0&&currentPage>recommended&&!continued.has(currentPage),message:t("learningMode.notice"),goLabel:t("learningMode.goRecommended"),continueLabel:t("learningMode.continueHere"),onGoRecommended:()=>changePage(recommended),onContinue:()=>setContinued(current=>new Set(current).add(currentPage))};const page=LESSON_4_PAGES[currentPage-1];const complete=REQUIRED.every(key=>activities.has(key))&&visited.has(6);const labels={backToMissions:t("mission4.shell.backToLearn"),missionCount:t("mission4.shell.lessonCount"),topicLabel:t("mission4.shell.topic"),pageCount:t("mission4.shell.pageCount",{current:currentPage,total:6}),back:t("mission4.shell.back"),next:t("mission4.shell.next"),prototypeEndAction:t("mission4.shell.incomplete"),prototypeLabel:t("mission4.shell.topic"),robotAlt:t("mission4.shell.robotAlt")};
function continueToNextLesson(){if(complete){setProgress(previous=>{const next=structuredClone(previous);next.missions[5]={progress:100,completed:true};writeProgress(next);return next});notify?.(t("mission4.actions.completedNotice"))}navigate("/mission/5-bias-paged")}
return <MissionLessonShell currentPage={currentPage} pageCount={6} onPageChange={changePage} onEnd={continueToNextLesson} onBackToMissions={()=>navigate("/missions")} title={t(page[1])} subtitle={t(page[2])} labels={{...labels,prototypeEndAction:"Next Lesson"}} recommendation={recommendation} rootClassName={`lesson-4-paged l4-page-${page[0]} paged-mission-playful playful-learning-scope`} robotImage={`/assets/img/${ROBOTS[currentPage-1]}`}><Lesson4Page1 active={currentPage===1} t={t}/><Lesson4Page2 active={currentPage===2} t={t} onComplete={()=>mark("scores")}/><Lesson4Page3 active={currentPage===3} t={t} onComplete={()=>mark("modes")}/><Lesson4Page4 active={currentPage===4} t={t} onComplete={()=>mark("placed")}/><Lesson4Page5 active={currentPage===5} t={t} onComplete={()=>mark("cycles")}/><Lesson4Page6 active={currentPage===6} t={t} complete={complete} onContinue={continueToNextLesson}/></MissionLessonShell>}
