const commonKeys = {
  "Room Map": null, "Continue": null, "Final Challenge": null, "Final Exit": null, "Language Model Escape Room": null,
  "Inventory": null, "Replay puzzle": null, "Enter room": null, "Locked": null, "Replay mode": null, "Crystal hunt": null,
  "Replay": null, "Open Final Exit": null, "Review Final Exit": null, "Lock question": null, "Option": null,
  "Hint": null, "Hide hint": null, "Show hint": null, "Reset room": null, "Activate lock": null,
  "Inspect console": null, "Console inspected": null, "Next clue": null, "Guide robot": null,
  "Token Workshop": null, "Context Chamber": null, "Connection Lab": null, "Prediction Machine": null, "Pattern Workshop": null,
  "Tokens": null, "Context": null, "Connections": null, "Prediction": null, "Patterns": null, "Training": null,
  "Token Crystal": null, "Context Crystal": null, "Connections Crystal": null, "Prediction Crystal": null, "Pattern Crystal": null,
  "Choose the real tokenizer split for one highlighted word.": null,
  "Find which tokens are available to the model right now.": null,
  "Decode the connection pattern to unlock the chamber.": null,
  "Power the prediction console and decode the next-token signal.": null,
  "Restore the model's training pattern to unlock the final crystal.": null,
  "Inspect door": null, "Activate tokeniser": null, "Verified example": null, "Tokenizer split": null, "Your idea": null,
  "The first Token includes the space before the word.": null,
  "Different tokenizers may split the same text differently.": null,
  "Which statement about tokenising &ldquo;unhelpful&rdquo; is the most accurate?": null,
  "Choose the most accurate statement. You do not need to reorder the sentence.": null,
  "It depends on the tokenizer. Different tokenizers may split &ldquo;unhelpful&rdquo; differently.": null,
  "Inspect console": null, "Activate context scanner": null, "Unlock context door": null, "Current context window": null,
  "Inside the window = available context": null, "Outside the window = may not be available right now": null,
  "Which tokens are available to the model right now?": null,
  "Choose the group that matches the tokens inside the glowing context window.": null,
  "The entire sentence": null, "Activate connection scanner": null, "Unlock connection door": null,
  "Focus token · opened": null, "Strong contribution": null, "Medium contribution": null, "Weak contribution": null,
  "Which token is shown contributing the most information to &ldquo;opened&rdquo;?": null,
  "Use the connection pattern above. You do not need to guess.": null,
  "Run prediction machine": null, "Unlock prediction door": null, "Next-token signal": null,
  "Higher probability = more likely right now.": null,
  "Which statement best matches the prediction shown by the machine?": null,
  "Read both the probabilities and the machine note.": null,
  "“book” will definitely be chosen next.": null,
  "“book” is the most likely option shown, but it is not guaranteed to be chosen.": null,
  "Every possible next token has the same chance.": null, "The model has already generated the whole sentence.": null,
  "Inspect training console": null, "Training records": null, "Reveal prediction": null,
  "Why can the training examples change the toy model's later prediction?": null,
  "The model stores every sentence and searches for an exact copy later.": null,
  "Repeated examples can strengthen learned patterns, which can influence later predictions.": null,
  "The model learns one perfect answer after seeing a single example.": null,
  "The examples directly tell the model what to say in every future conversation.": null,
  "Final Lock": null, "FINAL LOCK": null, "Power the Language Model Door": null, "Language Model Door": null,
  "Place crystals": null, "Form final crystal": null, "Solve final lock": null, "Empty slot": null,
  "Arrange the five ideas": null, "Reset cards": null, "Replay final puzzle": null, "Solve Final Lock": null,
  "Door open": null, "Ready to open": null, "Final crystal formed": null, "Waiting for crystals": null,
  "Collected crystals": null, "Final multicolour crystal": null,
  "Crystal collected": null,
  "Lookup ID": null, "From the Token Workshop": null, "Where does": null, "The tokenizer made the Token": null,
  "Now follow its ID.": null, "Drawer": null, "Look at the number on the ID card. Find the drawer with the same number.": null,
  "Drawer matched": null, "305 did not create these numbers.": null, "It only told the model where to find them.": null,
  "The model uses this learned number row in later calculations.": null,
  "Simplified teaching row — real models use much larger learned representations.": null,
  "Final lock": null, "Numbers Crystal ready": null, "Exactly — an ID is a lookup label.": null,
  "Collect the Numbers Crystal": null, "Stores the meaning": null, "Finds the number row": null, "Shows probability": null,
  "Hint: Think back to the verified example. Do all tokenizers have to split the same text in exactly the same way?": null,
  "Training happened earlier. When the model is used, text becomes tokens, available context is processed, information is combined, and a prediction is made.": null,
  "Drag each card into slots 1–5 in a sensible learning-to-prediction order. You can also click a card to fill the next empty slot, and click a filled slot to remove it.": null,
  "The reader found an ": null, "The little reader opened the ": null, "The little reader opened the book": null,
  "reader": null, "opened": null, "book": null, "little": null, "old": null, "The": null, "the": null,
  "The dragon sleeps in the ": null, "The dragon hides in the ": null, "The dragon waits in the ": null,
  "The dragon flew over the ": null, "The dragon returned to the ___": null, "cave": null, "castle": null, "forest": null
  ,"How Language Models Work — Escape Room": null, "Developer bridge console": null, "Room steps": null,
  "Text passes through the tokenizer and becomes Token pieces": null,
  "Tokens inside the current context window are available": null,
  "The new token book has joined the context": null,
  "Training examples lead through repeated small adjustments to learned patterns and later predictions": null,
  "Choose the most accurate statement about tokenising unhelpful": null,
  "Scene 1 of 3": null, "Scene 2 of 3": null, "Scene 3 of 3": null,
  "Token reader has ID 305": null, "Choose drawer 305": null,
  "Token reader uses ID 305 to find a learned number row": null,
  "Illustrative learned number row": null, "Choose what token ID 305 does": null,
  "Token sequence with the current context window highlighted": null, "Context window key": null,
  "Choose the tokens available inside the current context window": null,
  "Simplified connection pattern showing arrows toward the focus token opened": null,
  "Connection strength legend": null, "Choose the token with the strongest shown connection to opened": null,
  "Illustrative next-token probability signal": null, "Choose the statement that matches the prediction signal": null,
  "Simplified illustrative toy prediction": null, "Choose why training examples can change a later prediction": null,
  "Final exit steps": null, "slot": null, "cards": null
};

const messages = {
  zh: {
    "How Language Models Work — Escape Room":"语言模型如何工作 — 密室逃脱", "Developer bridge console":"开发者桥接控制台", "Room steps":"房间步骤", "Text passes through the tokenizer and becomes Token pieces":"文本经过分词器后变成 Token 片段", "Tokens inside the current context window are available":"当前上下文窗口内的 Token 可用", "The new token book has joined the context":"新 Token“书”已加入上下文", "Training examples lead through repeated small adjustments to learned patterns and later predictions":"训练示例通过反复的小幅调整形成学到的模式，并影响之后的预测", "Choose the most accurate statement about tokenising unhelpful":"选择关于 unhelpful 分词最准确的说法", "Scene 1 of 3":"场景 1 / 3", "Scene 2 of 3":"场景 2 / 3", "Scene 3 of 3":"场景 3 / 3", "Token reader has ID 305":"Token reader 的 ID 是 305", "Choose drawer 305":"选择 305 号抽屉", "Token reader uses ID 305 to find a learned number row":"Token reader 使用 ID 305 查找学到的数字行", "Illustrative learned number row":"示意性的已学习数字行", "Choose what token ID 305 does":"选择 Token ID 305 的作用", "Token sequence with the current context window highlighted":"高亮当前上下文窗口的 Token 序列", "Context window key":"上下文窗口图例", "Choose the tokens available inside the current context window":"选择当前上下文窗口内可用的 Token", "Simplified connection pattern showing arrows toward the focus token opened":"指向焦点 Token opened 的简化连接模式", "Connection strength legend":"连接强度图例", "Choose the token with the strongest shown connection to opened":"选择图中与 opened 连接最强的 Token", "Illustrative next-token probability signal":"示意性的下一个 Token 概率信号", "Choose the statement that matches the prediction signal":"选择符合预测信号的说法", "Simplified illustrative toy prediction":"简化的示意性玩具预测", "Choose why training examples can change a later prediction":"选择训练示例能改变之后预测的原因", "Final exit steps":"最终出口步骤", "slot":"槽位", "cards":"卡片",
    "Crystal collected":"已收集水晶",
    "Lookup ID":"查找 ID", "From the Token Workshop":"来自 Token 工坊", "Where does":"它会去哪里？", "The tokenizer made the Token":"分词器生成了 Token", "Now follow its ID.":"现在沿着它的 ID 查找。", "Drawer":"抽屉", "Look at the number on the ID card. Find the drawer with the same number.":"查看 ID 卡上的数字，找到编号相同的抽屉。", "Drawer matched":"抽屉匹配", "305 did not create these numbers.":"305 并没有创建这些数字。", "It only told the model where to find them.":"它只告诉模型去哪里找到它们。", "The model uses this learned number row in later calculations.":"模型会在后续计算中使用这组学到的数字。", "Simplified teaching row — real models use much larger learned representations.":"简化教学数字行——真实模型使用大得多的学习表示。", "Final lock":"最终锁", "Numbers Crystal ready":"数字水晶已就绪", "Exactly — an ID is a lookup label.":"正确——ID 是一个查找标签。", "Collect the Numbers Crystal":"收集数字水晶", "Stores the meaning":"存储含义", "Finds the number row":"找到数字行", "Shows probability":"显示概率", "Hint: Think back to the verified example. Do all tokenizers have to split the same text in exactly the same way?":"提示：回想已验证示例。所有分词器都必须以完全相同的方式拆分同一文本吗？",
    "Choose the real tokenizer split for one highlighted word.":"为高亮单词选择真实的分词方式。", "Find which tokens are available to the model right now.":"找出模型当前可用的 Token。", "Decode the connection pattern to unlock the chamber.":"解读连接模式，解锁密室。", "Power the prediction console and decode the next-token signal.":"启动预测控制台并解读下一个 Token 信号。", "Restore the model's training pattern to unlock the final crystal.":"恢复模型的训练模式，解锁最后一枚水晶。",
    "Inspect door":"检查门锁", "Activate tokeniser":"启动分词器", "Tokenizer split":"分词器拆分", "Your idea":"你的想法", "The first Token includes the space before the word.":"第一个 Token 包含单词前的空格。", "Choose the most accurate statement. You do not need to reorder the sentence.":"选择最准确的说法，无需重新排列句子。",
    "Choose the group that matches the tokens inside the glowing context window.":"选择与发光上下文窗口内 Token 匹配的一组。", "The entire sentence":"整个句子", "Use the connection pattern above. You do not need to guess.":"使用上方连接模式，无需猜测。", "Read both the probabilities and the machine note.":"同时阅读概率和机器说明。",
    "“book” will definitely be chosen next.":"接下来一定会选中“书”。", "“book” is the most likely option shown, but it is not guaranteed to be chosen.":"“书”是显示中最可能的选项，但不保证一定被选中。", "Every possible next token has the same chance.":"每个可能的下一个 Token 概率都相同。", "The model has already generated the whole sentence.":"模型已经生成了整个句子。",
    "The model stores every sentence and searches for an exact copy later.":"模型会存储每个句子，之后搜索完全相同的副本。", "Repeated examples can strengthen learned patterns, which can influence later predictions.":"重复示例能强化学到的模式，从而影响之后的预测。", "The model learns one perfect answer after seeing a single example.":"模型看一个示例就学会一个完美答案。", "The examples directly tell the model what to say in every future conversation.":"这些示例直接告诉模型未来每次对话该说什么。",
    "Final multicolour crystal":"最终多彩水晶", "Training happened earlier. When the model is used, text becomes tokens, available context is processed, information is combined, and a prediction is made.":"训练发生在更早阶段。使用模型时，文本变成 Token，模型处理可用上下文、组合信息并作出预测。", "Drag each card into slots 1–5 in a sensible learning-to-prediction order. You can also click a card to fill the next empty slot, and click a filled slot to remove it.":"按合理的学习到预测顺序，把卡片拖入 1–5 号槽位。也可点击卡片填入下一个空槽，点击已填槽位可移除卡片。",
    "The reader found an ":"读者发现了一个", "The little reader opened the ":"小读者打开了", "The little reader opened the book":"小读者打开了书", "reader":"读者", "opened":"打开了", "book":"书", "little":"小", "old":"旧", "The":"这个", "the":"这个", "The dragon sleeps in the ":"龙睡在", "The dragon hides in the ":"龙躲在", "The dragon waits in the ":"龙等在", "The dragon flew over the ":"龙飞过", "The dragon returned to the ___":"龙回到了 ___", "cave":"洞穴", "castle":"城堡", "forest":"森林",
    top: { eyebrow: "最终学习挑战", title: "语言模型密室逃脱", progress: "{{count}} / {{total}} 枚水晶" }, common: { roomMap: "房间地图", continue: "继续" },
    feedback: {
      tokenDefault:"Token 可以是完整单词、单词的一部分、标点或其他文本片段。", tokenInspected:"很好。门锁使用文本前，分词器必须先把文本拆成 Token。", tokenised:"这个已验证示例来自 Qwen2.5 分词器。现在把这个概念应用到另一个词。", tokenSelection:"已选择。启动门锁，与分词器进行比较。", tokenChoose:"请先选择一种 Token 说法。", tokenIncorrect:"还不对。不存在所有分词器都必须采用的唯一拆分方式；不同分词器可以用不同方式拆分同一文本。",
      numbersDefault:"请选择 ID 执行的作用。", contextDefault:"门锁扫描器离线。检查控制台以了解需要什么。", contextInspected:"控制台已检查。启动上下文扫描器，显示门锁能读取的 Token。", contextScanned:"扫描器已启动。发光框就是当前上下文窗口。", contextSelection:"已选择。检查发光窗口边界，然后解锁。", contextNeedScanner:"请先检查控制台并启动上下文扫描器。", contextChoose:"请选择发光上下文窗口内的 Token 组。", contextIncorrect:"还不对。查看发光窗口的边缘；本例中只有框内 Token 可用。",
      connectionDefault:"连接控制台离线。检查它以了解门锁需要什么。", connectionInspected:"门锁会组合多个 Token 位置的信息，但连接强度并不相同。", connectionScanned:"扫描器已启动。沿箭头看向焦点 Token，并比较粗细。", connectionSelection:"已选择。比较箭头粗细，然后解锁。", connectionNeedScanner:"请先检查控制台并启动连接扫描器。", connectionChoose:"请选择指向 opened 的最粗箭头对应的 Token。", connectionIncorrect:"还不对。无需猜哪个词最重要，只需比较图中的箭头粗细。",
      predictionDefault:"预测控制台离线。检查它以了解门锁需要的信号。", predictionInspected:"机器会比较多个可能的下一个 Token。", predictionRan:"预测信号已就绪。概率越高表示当前越可能，但不保证一定选中。", predictionSelection:"已选择。阅读最大概率和机器说明，然后解锁。", predictionNeedMachine:"请先检查控制台并运行预测机器。", predictionChoose:"请选择最符合预测信号的陈述。", predictionCorrect:"正确！“书”的显示概率最高，因此当前最可能，但高概率不保证一定被选中。", predictionIncorrect:"还不对。46% 使“书”成为显示中最可能的选项，但概率并不是保证。",
      patternDefault:"训练控制台离线。检查记录，了解模型如何学习。", patternInspected:"很好。控制台包含早期训练示例的记录。", patternRevealed:"这些示例影响了之后哪些结果更可能。现在解释原因。", patternSelection:"已选择。使用记录和后续预测启动门锁。", patternNeedPrediction:"请先检查训练控制台并显示后续预测。", patternChoose:"请选择把重复示例、学习到的模式和后续预测联系起来的解释。", patternCorrect:"模式已恢复。重复训练示例能强化所学模式，影响后续预测。", patternIncorrect:"机器仍锁定。一个示例不会变成存储答案；想想大量重复训练示例会随时间改变什么。"
    },
    exit:{fusionComplete:"最终水晶已形成，最终锁已启动。",complete:"最终锁已解开。训练发生在更早阶段；使用模型时，Token、上下文和连接共同导向一次下一个 Token 预测。",ready:"顺序正确。解开最终锁。",forming:"最终水晶正在形成……",orderPrompt:"把五个概念按顺序排列以解开最终锁。",placePrompt:"把五枚水晶放到模型门周围。",needsCrystals:"最终房间需要所有房间水晶。",reset:"最终锁已重置。放置五枚水晶后重新构建路径。",cardsCleared:"卡片已清空。重新构建学习到预测的路径。",fusionStarted:"五枚水晶已放置，融合开始。",placedProgress:"已放置 {{count}} / {{total}} 枚水晶。",slotOccupied:"该槽已有卡片。拖动交换，或选择空槽。",slotsFull:"五个槽已填满。检查顺序后解锁。",cardPlaced:"卡片已放入槽位。继续填满空槽。",unreadableCard:"无法读取该卡片。请重新拖动或点击。",wrongDropArea:"请把卡片放入最终锁槽位。",cardRemoved:"卡片已移除。请再次尝试顺序。",dropOnSlot:"请把卡片放到槽位或对应控制台内。",waitFusion:"请等待最终水晶形成。",placeAllFirst:"请先把所有水晶放到语言模型门周围。",fillSlots:"解锁前请填满所有空槽。",incorrectOrder:"最终锁仍关闭。检查顺序后重试。"},
    completion:{eyebrow:"最终挑战完成",title:"恭喜——语言模型之门已开启！",intro:"你恢复了全部五枚水晶，并重建了从学习到预测的路径。",summary:"语言模型把文本处理成 Token，使用可用的上下文，通过连接组合信息，预测下一个 Token，并依靠更早训练中学到的模式。",guide:"引导提示：你通过连接这些概念解开了最终锁，而不是把模型当成人。",recapTitle:"你解锁的五个概念",concepts:{tokens:{title:"Token",body:"文本被拆成模型可以处理的小片段。"},context:{title:"上下文",body:"较早且可用的 Token 会影响接下来可能出现什么。"},connections:{title:"连接",body:"来自不同 Token 位置的信息可以被组合。"},prediction:{title:"预测",body:"模型比较多种可能，并选择下一个 Token。"},patterns:{title:"学到的模式",body:"训练发生在更早阶段，并塑造了模型之后的预测。"}},return:"返回 LLM Explorer",replay:"重玩最终挑战"}
  },
  fr: {
    "How Language Models Work — Escape Room":"Fonctionnement des modèles de langage — Escape Room", "Developer bridge console":"Console de liaison développeur", "Room steps":"Étapes de la salle", "Text passes through the tokenizer and becomes Token pieces":"Le texte passe dans le tokenizer et devient des tokens", "Tokens inside the current context window are available":"Les tokens dans la fenêtre de contexte sont disponibles", "The new token book has joined the context":"Le nouveau token « book » a rejoint le contexte", "Training examples lead through repeated small adjustments to learned patterns and later predictions":"Les exemples produisent de petits ajustements répétés, des motifs appris puis des prédictions ultérieures", "Choose the most accurate statement about tokenising unhelpful":"Choisis l’affirmation la plus exacte sur la tokenisation de unhelpful", "Scene 1 of 3":"Scène 1 sur 3", "Scene 2 of 3":"Scène 2 sur 3", "Scene 3 of 3":"Scène 3 sur 3", "Token reader has ID 305":"Le token reader porte l’identifiant 305", "Choose drawer 305":"Choisir le tiroir 305", "Token reader uses ID 305 to find a learned number row":"Le token reader utilise l’identifiant 305 pour trouver une rangée apprise", "Illustrative learned number row":"Rangée de nombres apprise, à titre illustratif", "Choose what token ID 305 does":"Choisis le rôle de l’identifiant de token 305", "Token sequence with the current context window highlighted":"Séquence de tokens avec la fenêtre de contexte surlignée", "Context window key":"Légende de la fenêtre de contexte", "Choose the tokens available inside the current context window":"Choisis les tokens disponibles dans la fenêtre de contexte", "Simplified connection pattern showing arrows toward the focus token opened":"Motif simplifié montrant des flèches vers le token cible opened", "Connection strength legend":"Légende de la force des connexions", "Choose the token with the strongest shown connection to opened":"Choisis le token dont la connexion affichée vers opened est la plus forte", "Illustrative next-token probability signal":"Signal illustratif de probabilité du token suivant", "Choose the statement that matches the prediction signal":"Choisis l’affirmation correspondant au signal de prédiction", "Simplified illustrative toy prediction":"Prédiction jouet simplifiée et illustrative", "Choose why training examples can change a later prediction":"Choisis pourquoi les exemples peuvent modifier une prédiction ultérieure", "Final exit steps":"Étapes de la sortie finale", "slot":"emplacement", "cards":"cartes",
    "Crystal collected":"Cristal collecté",
    "Lookup ID":"Rechercher l’identifiant", "From the Token Workshop":"Depuis l’atelier des tokens", "Where does":"Où va-t-il ?", "The tokenizer made the Token":"Le tokenizer a produit le token", "Now follow its ID.":"Suis maintenant son identifiant.", "Drawer":"Tiroir", "Look at the number on the ID card. Find the drawer with the same number.":"Lis le numéro de la carte et trouve le tiroir correspondant.", "Drawer matched":"Tiroir correspondant", "305 did not create these numbers.":"305 n’a pas créé ces nombres.", "It only told the model where to find them.":"Il indique seulement au modèle où les trouver.", "The model uses this learned number row in later calculations.":"Le modèle utilise cette rangée apprise dans ses calculs suivants.", "Simplified teaching row — real models use much larger learned representations.":"Rangée pédagogique simplifiée — les vrais modèles utilisent des représentations bien plus grandes.", "Final lock":"Verrou final", "Numbers Crystal ready":"Cristal des nombres prêt", "Exactly — an ID is a lookup label.":"Exact — un identifiant est une étiquette de recherche.", "Collect the Numbers Crystal":"Collecter le cristal des nombres", "Stores the meaning":"Stocke le sens", "Finds the number row":"Trouve la rangée de nombres", "Shows probability":"Affiche une probabilité", "Hint: Think back to the verified example. Do all tokenizers have to split the same text in exactly the same way?":"Indice : repense à l’exemple vérifié. Tous les tokenizers doivent-ils découper le même texte exactement pareil ?",
    "Choose the real tokenizer split for one highlighted word.":"Choisis la véritable découpe du tokenizer pour le mot surligné.", "Find which tokens are available to the model right now.":"Trouve quels tokens sont actuellement disponibles pour le modèle.", "Decode the connection pattern to unlock the chamber.":"Décode le motif de connexions pour ouvrir la chambre.", "Power the prediction console and decode the next-token signal.":"Active la console et décode le signal du token suivant.", "Restore the model's training pattern to unlock the final crystal.":"Restaure le motif d’entraînement pour libérer le dernier cristal.",
    "Inspect door":"Inspecter la porte", "Activate tokeniser":"Activer le tokenizer", "Tokenizer split":"Découpe du tokenizer", "Your idea":"Ton idée", "The first Token includes the space before the word.":"Le premier token inclut l’espace avant le mot.", "Choose the most accurate statement. You do not need to reorder the sentence.":"Choisis l’affirmation la plus exacte, sans réordonner la phrase.",
    "Choose the group that matches the tokens inside the glowing context window.":"Choisis le groupe correspondant aux tokens dans la fenêtre lumineuse.", "The entire sentence":"La phrase entière", "Use the connection pattern above. You do not need to guess.":"Utilise le motif ci-dessus ; inutile de deviner.", "Read both the probabilities and the machine note.":"Lis les probabilités et la note de la machine.",
    "“book” will definitely be chosen next.":"« livre » sera forcément choisi ensuite.", "“book” is the most likely option shown, but it is not guaranteed to be chosen.":"« livre » est l’option affichée la plus probable, sans garantie.", "Every possible next token has the same chance.":"Tous les tokens suivants possibles ont la même probabilité.", "The model has already generated the whole sentence.":"Le modèle a déjà généré toute la phrase.",
    "The model stores every sentence and searches for an exact copy later.":"Le modèle mémorise chaque phrase et cherche ensuite une copie exacte.", "Repeated examples can strengthen learned patterns, which can influence later predictions.":"Des exemples répétés peuvent renforcer des motifs appris et influencer les prédictions ultérieures.", "The model learns one perfect answer after seeing a single example.":"Le modèle apprend une réponse parfaite après un seul exemple.", "The examples directly tell the model what to say in every future conversation.":"Les exemples dictent directement chaque réponse future au modèle.",
    "Final multicolour crystal":"Cristal final multicolore", "Training happened earlier. When the model is used, text becomes tokens, available context is processed, information is combined, and a prediction is made.":"L’entraînement a eu lieu plus tôt. À l’utilisation, le texte devient des tokens, le contexte disponible est traité, l’information est combinée et une prédiction est produite.", "Drag each card into slots 1–5 in a sensible learning-to-prediction order. You can also click a card to fill the next empty slot, and click a filled slot to remove it.":"Fais glisser les cartes dans les emplacements 1 à 5 selon un ordre logique de l’apprentissage à la prédiction. Tu peux aussi cliquer pour remplir ou vider un emplacement.",
    "The reader found an ":"Le lecteur a trouvé un ", "The little reader opened the ":"Le petit lecteur a ouvert le ", "The little reader opened the book":"Le petit lecteur a ouvert le livre", "reader":"lecteur", "opened":"a ouvert", "book":"livre", "little":"petit", "old":"vieux", "The":"Le", "the":"le", "The dragon sleeps in the ":"Le dragon dort dans la ", "The dragon hides in the ":"Le dragon se cache dans la ", "The dragon waits in the ":"Le dragon attend dans la ", "The dragon flew over the ":"Le dragon a survolé la ", "The dragon returned to the ___":"Le dragon est retourné au ___", "cave":"grotte", "castle":"château", "forest":"forêt",
    top:{eyebrow:"Défi d’apprentissage final",title:"Escape Room du modèle de langage",progress:"{{count}} / {{total}} cristaux"},common:{roomMap:"Carte des salles",continue:"Continuer"},
    feedback:{
      tokenDefault:"Un token peut être un mot, une partie de mot, un signe de ponctuation ou un autre fragment de texte.",tokenInspected:"Bien. Le tokenizer doit découper le texte en tokens avant que le verrou puisse l’utiliser.",tokenised:"Cet exemple vérifié vient du tokenizer Qwen2.5. Applique maintenant cette idée à un autre mot.",tokenSelection:"Sélection prête. Active le verrou pour comparer avec le tokenizer.",tokenChoose:"Choisis une proposition avant d’activer le verrou.",tokenIncorrect:"Pas tout à fait. Il n’existe pas de découpage unique imposé à tous les tokenizers ; ils peuvent découper le même texte différemment.",
      numbersDefault:"Choisis le rôle joué par l’identifiant.",contextDefault:"Le scanner de la porte est hors ligne. Inspecte la console pour découvrir ce dont il a besoin.",contextInspected:"Console inspectée. Active le scanner de contexte pour révéler les tokens lisibles.",contextScanned:"Scanner actif. Le cadre lumineux est la fenêtre de contexte actuelle.",contextSelection:"Sélection prête. Vérifie les limites du cadre, puis déverrouille la porte.",contextNeedScanner:"Inspecte la console et active le scanner de contexte.",contextChoose:"Choisis le groupe de tokens dans la fenêtre lumineuse.",contextIncorrect:"Pas tout à fait. Regarde les bords de la fenêtre : seuls les tokens à l’intérieur sont disponibles ici.",
      connectionDefault:"La console des connexions est hors ligne. Inspecte-la.",connectionInspected:"Le verrou combine l’information de plusieurs positions, mais les connexions n’ont pas toutes la même force.",connectionScanned:"Scanner actif. Suis les flèches vers le token cible et compare leur épaisseur.",connectionSelection:"Sélection prête. Compare les flèches, puis déverrouille la porte.",connectionNeedScanner:"Inspecte la console et active le scanner des connexions.",connectionChoose:"Choisis le token dont la flèche vers « opened » est la plus épaisse.",connectionIncorrect:"Pas tout à fait. Ne devine pas le mot le plus important ; compare simplement l’épaisseur des flèches.",
      predictionDefault:"La console de prédiction est hors ligne. Inspecte-la.",predictionInspected:"La machine compare plusieurs tokens suivants possibles.",predictionRan:"Signal prêt. Une probabilité plus élevée signifie plus probable maintenant, pas garanti.",predictionSelection:"Sélection prête. Lis la plus grande probabilité et la note, puis déverrouille.",predictionNeedMachine:"Inspecte la console et lance la machine de prédiction.",predictionChoose:"Choisis l’énoncé qui correspond au signal affiché.",predictionCorrect:"Correct ! « book » a la probabilité la plus élevée : c’est l’option la plus probable, sans être garantie.",predictionIncorrect:"Pas tout à fait. 46 % rend « book » le plus probable parmi les choix affichés, mais ce n’est pas une garantie.",
      patternDefault:"La console d’entraînement est hors ligne. Inspecte ses archives.",patternInspected:"Bien. La console contient des exemples d’entraînement antérieurs.",patternRevealed:"Ces exemples ont influencé ce qui est devenu plus probable ensuite. Explique pourquoi.",patternSelection:"Sélection prête. Utilise les archives et la prédiction pour activer le verrou.",patternNeedPrediction:"Inspecte la console et révèle la prédiction ultérieure.",patternChoose:"Choisis l’explication reliant exemples répétés, motifs appris et prédictions ultérieures.",patternCorrect:"Motif restauré. Des exemples répétés peuvent renforcer des motifs appris qui influencent les prédictions.",patternIncorrect:"Le moteur reste verrouillé. Un exemple ne devient pas une réponse mémorisée ; pense à ce que de nombreux exemples peuvent modifier avec le temps."
    },
    exit:{fusionComplete:"Cristal final formé. Le verrou final est actif.",complete:"Verrou final résolu. L’entraînement a eu lieu plus tôt ; lors de l’utilisation, tokens, contexte et connexions mènent à une prédiction du token suivant.",ready:"L’ordre est correct. Résous le verrou final.",forming:"Formation du cristal final…",orderPrompt:"Mets les cinq idées dans l’ordre pour résoudre le verrou final.",placePrompt:"Place les cinq cristaux autour de la porte du modèle.",needsCrystals:"La salle finale exige tous les cristaux.",reset:"Verrou réinitialisé. Place les cinq cristaux puis reconstruis le chemin.",cardsCleared:"Cartes retirées. Reconstruis le chemin de l’apprentissage à la prédiction.",fusionStarted:"Cinq cristaux placés. Fusion lancée.",placedProgress:"{{count}} / {{total}} cristaux placés.",slotOccupied:"Cet emplacement contient déjà une carte. Échange-la ou choisis un emplacement vide.",slotsFull:"Les cinq emplacements sont remplis. Vérifie l’ordre puis résous le verrou.",cardPlaced:"Carte placée. Continue à remplir les emplacements.",unreadableCard:"Carte illisible. Fais-la glisser à nouveau ou clique dessus.",wrongDropArea:"Dépose la carte dans les emplacements du verrou final.",cardRemoved:"Carte retirée. Réessaie l’ordre.",dropOnSlot:"Dépose la carte sur un emplacement ou dans la console correspondante.",waitFusion:"Attends la formation du cristal final.",placeAllFirst:"Place d’abord tous les cristaux autour de la porte.",fillSlots:"Remplis tous les emplacements avant de résoudre le verrou.",incorrectOrder:"Le verrou final reste fermé. Vérifie l’ordre et réessaie."},
    completion:{eyebrow:"Défi final terminé",title:"Félicitations — la porte du modèle de langage est ouverte !",intro:"Tu as restauré les cinq cristaux et reconstruit le chemin de l’apprentissage à la prédiction.",summary:"Un modèle de langage traite le texte en tokens, utilise le contexte disponible, combine l’information par des connexions, prédit le token suivant et s’appuie sur des motifs appris plus tôt.",guide:"Note du guide : tu as résolu le verrou en reliant les idées, sans traiter le modèle comme une personne.",recapTitle:"Les cinq idées déverrouillées",concepts:{tokens:{title:"Tokens",body:"Le texte est découpé en petits éléments que le modèle peut traiter."},context:{title:"Contexte",body:"Les tokens antérieurs disponibles influencent ce qui peut suivre."},connections:{title:"Connexions",body:"L’information de différentes positions de tokens peut être combinée."},prediction:{title:"Prédiction",body:"Le modèle compare des possibilités et choisit le token suivant."},patterns:{title:"Motifs appris",body:"L’entraînement a eu lieu plus tôt et a façonné les prédictions ultérieures."}},return:"Retour à LLM Explorer",replay:"Rejouer le défi final"}
  },
  de: {
    "How Language Models Work — Escape Room":"Wie Sprachmodelle funktionieren — Escape Room", "Developer bridge console":"Entwickler-Bridge-Konsole", "Room steps":"Raumschritte", "Text passes through the tokenizer and becomes Token pieces":"Text durchläuft den Tokenizer und wird zu Token-Teilen", "Tokens inside the current context window are available":"Tokens im aktuellen Kontextfenster sind verfügbar", "The new token book has joined the context":"Das neue Token „book“ ist nun im Kontext", "Training examples lead through repeated small adjustments to learned patterns and later predictions":"Trainingsbeispiele führen über wiederholte kleine Anpassungen zu gelernten Mustern und späteren Vorhersagen", "Choose the most accurate statement about tokenising unhelpful":"Wähle die genaueste Aussage zur Tokenisierung von unhelpful", "Scene 1 of 3":"Szene 1 von 3", "Scene 2 of 3":"Szene 2 von 3", "Scene 3 of 3":"Szene 3 von 3", "Token reader has ID 305":"Das Token reader hat die ID 305", "Choose drawer 305":"Schublade 305 wählen", "Token reader uses ID 305 to find a learned number row":"Das Token reader nutzt ID 305, um eine gelernte Zahlenzeile zu finden", "Illustrative learned number row":"Veranschaulichte gelernte Zahlenzeile", "Choose what token ID 305 does":"Wähle, was die Token-ID 305 bewirkt", "Token sequence with the current context window highlighted":"Tokenfolge mit hervorgehobenem aktuellem Kontextfenster", "Context window key":"Legende des Kontextfensters", "Choose the tokens available inside the current context window":"Wähle die im aktuellen Kontextfenster verfügbaren Tokens", "Simplified connection pattern showing arrows toward the focus token opened":"Vereinfachtes Verbindungsmuster mit Pfeilen zum Fokus-Token opened", "Connection strength legend":"Legende der Verbindungsstärke", "Choose the token with the strongest shown connection to opened":"Wähle das Token mit der stärksten gezeigten Verbindung zu opened", "Illustrative next-token probability signal":"Veranschaulichtes Wahrscheinlichkeitssignal für das nächste Token", "Choose the statement that matches the prediction signal":"Wähle die zum Vorhersagesignal passende Aussage", "Simplified illustrative toy prediction":"Vereinfachte veranschaulichte Spielzeugvorhersage", "Choose why training examples can change a later prediction":"Wähle, warum Trainingsbeispiele eine spätere Vorhersage verändern können", "Final exit steps":"Schritte des Finalausgangs", "slot":"Platz", "cards":"Karten",
    "Crystal collected":"Kristall gesammelt",
    "Lookup ID":"ID nachschlagen", "From the Token Workshop":"Aus der Token-Werkstatt", "Where does":"Wohin führt es?", "The tokenizer made the Token":"Der Tokenizer erzeugte das Token", "Now follow its ID.":"Folge nun seiner ID.", "Drawer":"Schublade", "Look at the number on the ID card. Find the drawer with the same number.":"Lies die Zahl auf der ID-Karte und finde die passende Schublade.", "Drawer matched":"Schublade gefunden", "305 did not create these numbers.":"305 hat diese Zahlen nicht erzeugt.", "It only told the model where to find them.":"Die ID sagt dem Modell nur, wo es sie findet.", "The model uses this learned number row in later calculations.":"Das Modell nutzt diese gelernte Zahlenreihe in späteren Berechnungen.", "Simplified teaching row — real models use much larger learned representations.":"Vereinfachte Lernreihe — echte Modelle verwenden viel größere Darstellungen.", "Final lock":"Finales Schloss", "Numbers Crystal ready":"Zahlenkristall bereit", "Exactly — an ID is a lookup label.":"Genau — eine ID ist eine Nachschlagekennzeichnung.", "Collect the Numbers Crystal":"Zahlenkristall sammeln", "Stores the meaning":"Speichert die Bedeutung", "Finds the number row":"Findet die Zahlenreihe", "Shows probability":"Zeigt Wahrscheinlichkeit", "Hint: Think back to the verified example. Do all tokenizers have to split the same text in exactly the same way?":"Hinweis: Denke an das geprüfte Beispiel. Müssen alle Tokenizer denselben Text genau gleich zerlegen?",
    "Choose the real tokenizer split for one highlighted word.":"Wähle die echte Tokenizer-Aufteilung für das markierte Wort.", "Find which tokens are available to the model right now.":"Finde heraus, welche Tokens dem Modell jetzt zur Verfügung stehen.", "Decode the connection pattern to unlock the chamber.":"Entschlüssele das Verbindungsmuster, um die Kammer zu öffnen.", "Power the prediction console and decode the next-token signal.":"Aktiviere die Konsole und entschlüssele das Nächstes-Token-Signal.", "Restore the model's training pattern to unlock the final crystal.":"Stelle das Trainingsmuster wieder her, um den letzten Kristall zu erhalten.",
    "Inspect door":"Tür prüfen", "Activate tokeniser":"Tokenizer aktivieren", "Tokenizer split":"Tokenizer-Aufteilung", "Your idea":"Deine Idee", "The first Token includes the space before the word.":"Das erste Token enthält das Leerzeichen vor dem Wort.", "Choose the most accurate statement. You do not need to reorder the sentence.":"Wähle die genaueste Aussage; der Satz muss nicht neu geordnet werden.",
    "Choose the group that matches the tokens inside the glowing context window.":"Wähle die Gruppe der Tokens im leuchtenden Kontextfenster.", "The entire sentence":"Der ganze Satz", "Use the connection pattern above. You do not need to guess.":"Nutze das Muster oben; du musst nicht raten.", "Read both the probabilities and the machine note.":"Lies die Wahrscheinlichkeiten und den Maschinenhinweis.",
    "“book” will definitely be chosen next.":"„Buch“ wird als Nächstes sicher gewählt.", "“book” is the most likely option shown, but it is not guaranteed to be chosen.":"„Buch“ ist die wahrscheinlichste gezeigte Option, aber nicht garantiert.", "Every possible next token has the same chance.":"Jedes mögliche nächste Token hat dieselbe Wahrscheinlichkeit.", "The model has already generated the whole sentence.":"Das Modell hat bereits den ganzen Satz erzeugt.",
    "The model stores every sentence and searches for an exact copy later.":"Das Modell speichert jeden Satz und sucht später nach einer exakten Kopie.", "Repeated examples can strengthen learned patterns, which can influence later predictions.":"Wiederholte Beispiele können gelernte Muster stärken und spätere Vorhersagen beeinflussen.", "The model learns one perfect answer after seeing a single example.":"Das Modell lernt nach einem Beispiel eine perfekte Antwort.", "The examples directly tell the model what to say in every future conversation.":"Die Beispiele schreiben dem Modell jede zukünftige Antwort direkt vor.",
    "Final multicolour crystal":"Finaler mehrfarbiger Kristall", "Training happened earlier. When the model is used, text becomes tokens, available context is processed, information is combined, and a prediction is made.":"Das Training fand früher statt. Bei der Nutzung wird Text zu Tokens, verfügbarer Kontext verarbeitet, Information kombiniert und eine Vorhersage erzeugt.", "Drag each card into slots 1–5 in a sensible learning-to-prediction order. You can also click a card to fill the next empty slot, and click a filled slot to remove it.":"Ziehe die Karten in einer sinnvollen Reihenfolge von Lernen zu Vorhersage auf die Plätze 1–5. Du kannst Karten auch anklicken, um Plätze zu füllen oder zu leeren.",
    "The reader found an ":"Der Leser fand einen ", "The little reader opened the ":"Der kleine Leser öffnete das ", "The little reader opened the book":"Der kleine Leser öffnete das Buch", "reader":"Leser", "opened":"öffnete", "book":"Buch", "little":"klein", "old":"alt", "The":"Der", "the":"der", "The dragon sleeps in the ":"Der Drache schläft in der ", "The dragon hides in the ":"Der Drache versteckt sich in der ", "The dragon waits in the ":"Der Drache wartet in der ", "The dragon flew over the ":"Der Drache flog über den ", "The dragon returned to the ___":"Der Drache kehrte zum ___ zurück", "cave":"Höhle", "castle":"Schloss", "forest":"Wald",
    top:{eyebrow:"Finale Lernaufgabe",title:"Sprachmodell-Escape-Room",progress:"{{count}} / {{total}} Kristalle"},common:{roomMap:"Raumkarte",continue:"Weiter"},
    feedback:{
      tokenDefault:"Ein Token kann ein ganzes Wort, ein Wortteil, Satzzeichen oder ein anderes Textstück sein.",tokenInspected:"Gut. Der Tokenizer muss Text zuerst in Tokens zerlegen.",tokenised:"Dieses geprüfte Beispiel stammt vom Qwen2.5-Tokenizer. Übertrage die Idee nun auf ein anderes Wort.",tokenSelection:"Auswahl bereit. Aktiviere das Schloss zum Vergleich.",tokenChoose:"Wähle zuerst eine Aussage aus.",tokenIncorrect:"Noch nicht. Es gibt keine für alle Tokenizer verbindliche Aufteilung; derselbe Text kann unterschiedlich zerlegt werden.",
      numbersDefault:"Wähle die Aufgabe der ID.",contextDefault:"Der Türscanner ist offline. Prüfe die Konsole.",contextInspected:"Konsole geprüft. Aktiviere den Kontextscanner, um die lesbaren Tokens zu zeigen.",contextScanned:"Scanner aktiv. Der leuchtende Rahmen ist das aktuelle Kontextfenster.",contextSelection:"Auswahl bereit. Prüfe den Rahmen und öffne dann die Tür.",contextNeedScanner:"Prüfe die Konsole und aktiviere den Kontextscanner.",contextChoose:"Wähle die Token-Gruppe im leuchtenden Kontextfenster.",contextIncorrect:"Noch nicht. Nur die Tokens innerhalb des leuchtenden Rahmens sind hier verfügbar.",
      connectionDefault:"Die Verbindungskonsole ist offline. Prüfe sie.",connectionInspected:"Das Schloss kombiniert Informationen mehrerer Token-Positionen, doch die Verbindungen sind unterschiedlich stark.",connectionScanned:"Scanner aktiv. Folge den Pfeilen zum Fokus-Token und vergleiche ihre Stärke.",connectionSelection:"Auswahl bereit. Vergleiche die Pfeile und öffne dann die Tür.",connectionNeedScanner:"Prüfe die Konsole und aktiviere den Verbindungsscanner.",connectionChoose:"Wähle das Token mit dem dicksten Pfeil zu „opened“.",connectionIncorrect:"Noch nicht. Du musst nicht raten; vergleiche nur die Pfeildicken.",
      predictionDefault:"Die Vorhersagekonsole ist offline. Prüfe sie.",predictionInspected:"Die Maschine vergleicht mehrere mögliche nächste Tokens.",predictionRan:"Signal bereit. Höhere Wahrscheinlichkeit bedeutet momentan wahrscheinlicher, nicht garantiert.",predictionSelection:"Auswahl bereit. Lies die höchste Wahrscheinlichkeit und den Hinweis.",predictionNeedMachine:"Prüfe die Konsole und starte die Vorhersagemaschine.",predictionChoose:"Wähle die Aussage, die zum Signal passt.",predictionCorrect:"Richtig! „book“ hat die höchste gezeigte Wahrscheinlichkeit, ist aber nicht garantiert.",predictionIncorrect:"Noch nicht. 46 % macht „book“ zur wahrscheinlichsten gezeigten Option, aber nicht zu einer Garantie.",
      patternDefault:"Die Trainingskonsole ist offline. Prüfe ihre Aufzeichnungen.",patternInspected:"Gut. Die Konsole enthält frühere Trainingsbeispiele.",patternRevealed:"Die Beispiele beeinflussten, was später wahrscheinlicher wurde. Erkläre warum.",patternSelection:"Auswahl bereit. Nutze Aufzeichnungen und Vorhersage für das Schloss.",patternNeedPrediction:"Prüfe die Trainingskonsole und zeige die spätere Vorhersage.",patternChoose:"Wähle die Erklärung, die wiederholte Beispiele, gelernte Muster und spätere Vorhersagen verbindet.",patternCorrect:"Muster wiederhergestellt. Wiederholte Beispiele können gelernte Muster stärken und spätere Vorhersagen beeinflussen.",patternIncorrect:"Der Mechanismus bleibt gesperrt. Ein Beispiel wird nicht als Antwort gespeichert; denke an Veränderungen durch viele Beispiele."
    },
    exit:{fusionComplete:"Finaler Kristall geformt. Das finale Schloss ist aktiv.",complete:"Finales Schloss gelöst. Das Training geschah früher; bei der Nutzung führen Tokens, Kontext und Verbindungen zu einer nächsten Token-Vorhersage.",ready:"Die Reihenfolge stimmt. Löse das finale Schloss.",forming:"Finaler Kristall wird geformt…",orderPrompt:"Ordne die fünf Ideen, um das finale Schloss zu lösen.",placePrompt:"Platziere alle fünf Kristalle um die Modelltür.",needsCrystals:"Der finale Raum benötigt alle Kristalle.",reset:"Finales Schloss zurückgesetzt. Platziere die Kristalle und baue den Pfad neu.",cardsCleared:"Karten entfernt. Baue den Lern-zur-Vorhersage-Pfad neu.",fusionStarted:"Fünf Kristalle platziert. Fusion gestartet.",placedProgress:"{{count}} / {{total}} Kristalle platziert.",slotOccupied:"Dieser Platz ist belegt. Tausche die Karte oder wähle einen freien Platz.",slotsFull:"Alle fünf Plätze sind gefüllt. Prüfe die Reihenfolge und löse das Schloss.",cardPlaced:"Karte platziert. Fülle die übrigen Plätze.",unreadableCard:"Karte konnte nicht gelesen werden. Ziehe sie erneut oder klicke sie an.",wrongDropArea:"Lege die Karte in die Plätze des finalen Schlosses.",cardRemoved:"Karte entfernt. Versuche die Reihenfolge erneut.",dropOnSlot:"Lege die Karte auf einen Platz oder in die passende Konsole.",waitFusion:"Warte, bis der finale Kristall geformt ist.",placeAllFirst:"Platziere zuerst alle Kristalle um die Tür.",fillSlots:"Fülle alle leeren Plätze, bevor du das Schloss löst.",incorrectOrder:"Das finale Schloss bleibt geschlossen. Prüfe die Reihenfolge und versuche es erneut."},
    completion:{eyebrow:"Finale Challenge abgeschlossen",title:"Glückwunsch — die Sprachmodelltür ist offen!",intro:"Du hast alle fünf Kristalle wiederhergestellt und den Weg vom Lernen zur Vorhersage aufgebaut.",summary:"Sprachmodelle verarbeiten Text als Tokens, nutzen verfügbaren Kontext, kombinieren Informationen über Verbindungen, sagen das nächste Token voraus und verwenden früher gelernte Muster.",guide:"Hinweis des Guides: Du hast das Schloss durch das Verbinden der Ideen gelöst — nicht indem du das Modell wie eine Person behandelst.",recapTitle:"Fünf freigeschaltete Ideen",concepts:{tokens:{title:"Tokens",body:"Text wird in kleinere Teile zerlegt, die das Modell verarbeiten kann."},context:{title:"Kontext",body:"Frühere verfügbare Tokens beeinflussen, was als Nächstes kommen kann."},connections:{title:"Verbindungen",body:"Informationen aus verschiedenen Token-Positionen können kombiniert werden."},prediction:{title:"Vorhersage",body:"Das Modell vergleicht Möglichkeiten und wählt ein nächstes Token."},patterns:{title:"Gelernte Muster",body:"Das Training fand früher statt und prägte spätere Vorhersagen."}},return:"Zurück zu LLM Explorer",replay:"Finale Challenge wiederholen"}
  }
};

const sharedTranslations = {
  zh: ["房间地图","继续","最终挑战","最终出口","语言模型密室逃脱","物品栏","重玩谜题","进入房间","已锁定","重玩模式","水晶搜寻","重玩","打开最终出口","查看最终出口","门锁问题","选项","提示","隐藏提示","显示提示","重置房间","启动门锁","检查控制台","控制台已检查","下一条线索","引导机器人","Token 工坊","上下文密室","连接实验室","预测机器","模式工坊","Token","上下文","连接","预测","模式","训练","Token 水晶","上下文水晶","连接水晶","预测水晶","模式水晶"],
  fr: ["Carte des salles","Continuer","Défi final","Sortie finale","Escape Room du modèle de langage","Inventaire","Rejouer l’énigme","Entrer","Verrouillé","Mode replay","Chasse au cristal","Rejouer","Ouvrir la sortie finale","Revoir la sortie finale","Question du verrou","Option","Indice","Masquer l’indice","Afficher l’indice","Réinitialiser la salle","Activer le verrou","Inspecter la console","Console inspectée","Indice suivant","Robot-guide","Atelier des tokens","Chambre du contexte","Laboratoire des connexions","Machine de prédiction","Atelier des motifs","Tokens","Contexte","Connexions","Prédiction","Motifs","Entraînement","Cristal des tokens","Cristal du contexte","Cristal des connexions","Cristal de prédiction","Cristal des motifs"],
  de: ["Raumkarte","Weiter","Finale Challenge","Finalausgang","Sprachmodell-Escape-Room","Inventar","Rätsel wiederholen","Raum betreten","Gesperrt","Wiederholungsmodus","Kristallsuche","Wiederholen","Finalausgang öffnen","Finalausgang ansehen","Schlossfrage","Option","Hinweis","Hinweis ausblenden","Hinweis anzeigen","Raum zurücksetzen","Schloss aktivieren","Konsole prüfen","Konsole geprüft","Nächster Hinweis","Roboter-Guide","Token-Werkstatt","Kontextkammer","Verbindungslabor","Vorhersagemaschine","Musterwerkstatt","Tokens","Kontext","Verbindungen","Vorhersage","Muster","Training","Token-Kristall","Kontextkristall","Verbindungskristall","Vorhersagekristall","Musterkristall"]
};

const activeReplacements = {
  zh: {
    "Restore five crystals with your guide. Each room reviews one of the five lessons about how language models process text, predict, and learn.": "和向导一起恢复五枚水晶。每个房间复习一课，涵盖语言模型如何处理文本、预测和学习。",
    "Start Room 1":"开始房间 1", "Continue adventure":"继续冒险", "Choose an unlocked room. Completed rooms can be replayed.":"选择已解锁房间。已完成房间可以重玩。",
    "The lock receives text as token pieces, not one whole block.":"门锁接收的是 Token 片段，而不是整块文本。", "Verified Qwen2.5 tokenizer":"已验证的 Qwen2.5 分词器", "Verified example":"已验证示例", "Different tokenizers may split the same text differently.":"不同分词器可能会以不同方式拆分同一文本。", "Which statement about tokenising &ldquo;unhelpful&rdquo; is the most accurate?":"关于 “unhelpful” 的分词，哪种说法最准确？", "It depends on the tokenizer. Different tokenizers may split &ldquo;unhelpful&rdquo; differently.":"取决于分词器。不同分词器可能会以不同方式拆分 “unhelpful”。",
    "Door scanner offline":"门锁扫描器离线", "Activate context scanner":"启动上下文扫描器", "Current context window":"当前上下文窗口", "Inside the window = available context":"窗口内 = 可用上下文", "Outside the window = may not be available right now":"窗口外 = 当前可能不可用", "Which tokens are available to the model right now?":"模型当前可以使用哪些 Token？", "Unlock context door":"解锁上下文门",
    "Connection console offline":"连接控制台离线", "Activate connection scanner":"启动连接扫描器", "Focus token · opened":"焦点 Token · opened", "Strong contribution":"强贡献", "Medium contribution":"中等贡献", "Weak contribution":"弱贡献", "Which token is shown contributing the most information to &ldquo;opened&rdquo;?":"图中哪个 Token 对 “opened” 的信息贡献最多？", "Unlock connection door":"解锁连接门",
    "Prediction console offline":"预测控制台离线", "Run prediction machine":"运行预测机器", "Next-token signal":"下一个 Token 信号", "Higher probability = more likely right now.":"概率越高 = 当前越可能。", "Which statement best matches the prediction shown by the machine?":"哪种说法最符合机器显示的预测？", "Unlock prediction door":"解锁预测门",
    "Training console offline":"训练控制台离线", "Inspect training console":"检查训练控制台", "Training records":"训练记录", "Reveal prediction":"显示预测", "Why can the training examples change the toy model's later prediction?":"为什么训练示例会改变玩具模型之后的预测？",
    "Power the Language Model Door":"为语言模型门供能", "Final room not ready":"最终房间尚未就绪", "Final Lock":"最终锁", "FINAL LOCK":"最终锁", "Place crystals":"放置水晶", "Form final crystal":"形成最终水晶", "Solve final lock":"解开最终锁", "Language Model Door":"语言模型门", "Waiting for crystals":"等待水晶", "Collected crystals":"已收集水晶", "Arrange the five ideas":"排列五个概念", "Empty slot":"空槽", "Reset cards":"重置卡片", "Replay final puzzle":"重玩最终谜题", "Solve Final Lock":"解开最终锁", "Door open":"门已打开", "Ready to open":"可以开启", "Final crystal formed":"最终水晶已形成"
  },
  fr: {
    "Restore five crystals with your guide. Each room reviews one of the five lessons about how language models process text, predict, and learn.":"Restaure cinq cristaux avec ton guide. Chaque salle révise une leçon sur le traitement du texte, la prédiction et l’apprentissage.", "Start Room 1":"Commencer la salle 1", "Continue adventure":"Continuer l’aventure", "Choose an unlocked room. Completed rooms can be replayed.":"Choisis une salle déverrouillée. Les salles terminées peuvent être rejouées.",
    "The lock receives text as token pieces, not one whole block.":"Le verrou reçoit le texte sous forme de tokens, pas comme un bloc entier.", "Verified Qwen2.5 tokenizer":"Tokenizer Qwen2.5 vérifié", "Verified example":"Exemple vérifié", "Different tokenizers may split the same text differently.":"Différents tokenizers peuvent découper le même texte différemment.", "Which statement about tokenising &ldquo;unhelpful&rdquo; is the most accurate?":"Quelle affirmation sur la tokenisation de « unhelpful » est la plus exacte ?", "It depends on the tokenizer. Different tokenizers may split &ldquo;unhelpful&rdquo; differently.":"Cela dépend du tokenizer. Différents tokenizers peuvent découper « unhelpful » différemment.",
    "Door scanner offline":"Scanner de porte hors ligne", "Activate context scanner":"Activer le scanner de contexte", "Current context window":"Fenêtre de contexte actuelle", "Inside the window = available context":"Dans la fenêtre = contexte disponible", "Outside the window = may not be available right now":"Hors de la fenêtre = peut être indisponible", "Which tokens are available to the model right now?":"Quels tokens sont disponibles pour le modèle maintenant ?", "Unlock context door":"Déverrouiller la porte du contexte",
    "Connection console offline":"Console des connexions hors ligne", "Activate connection scanner":"Activer le scanner des connexions", "Focus token · opened":"Token cible · opened", "Strong contribution":"Contribution forte", "Medium contribution":"Contribution moyenne", "Weak contribution":"Contribution faible", "Which token is shown contributing the most information to &ldquo;opened&rdquo;?":"Quel token contribue le plus d’information à « opened » ?", "Unlock connection door":"Déverrouiller la porte des connexions",
    "Prediction console offline":"Console de prédiction hors ligne", "Run prediction machine":"Lancer la machine de prédiction", "Next-token signal":"Signal du token suivant", "Higher probability = more likely right now.":"Probabilité plus élevée = plus probable maintenant.", "Which statement best matches the prediction shown by the machine?":"Quelle affirmation correspond le mieux à la prédiction affichée ?", "Unlock prediction door":"Déverrouiller la porte de prédiction",
    "Training console offline":"Console d’entraînement hors ligne", "Inspect training console":"Inspecter la console d’entraînement", "Training records":"Archives d’entraînement", "Reveal prediction":"Révéler la prédiction", "Why can the training examples change the toy model's later prediction?":"Pourquoi les exemples d’entraînement peuvent-ils modifier une prédiction ultérieure ?",
    "Power the Language Model Door":"Alimenter la porte du modèle de langage", "Final room not ready":"Salle finale non disponible", "Final Lock":"Verrou final", "FINAL LOCK":"VERROU FINAL", "Place crystals":"Placer les cristaux", "Form final crystal":"Former le cristal final", "Solve final lock":"Résoudre le verrou final", "Language Model Door":"Porte du modèle de langage", "Waiting for crystals":"En attente des cristaux", "Collected crystals":"Cristaux collectés", "Arrange the five ideas":"Ordonner les cinq idées", "Empty slot":"Emplacement vide", "Reset cards":"Réinitialiser les cartes", "Replay final puzzle":"Rejouer l’énigme finale", "Solve Final Lock":"Résoudre le verrou final", "Door open":"Porte ouverte", "Ready to open":"Prêt à ouvrir", "Final crystal formed":"Cristal final formé"
  },
  de: {
    "Restore five crystals with your guide. Each room reviews one of the five lessons about how language models process text, predict, and learn.":"Stelle mit deinem Guide fünf Kristalle wieder her. Jeder Raum wiederholt eine Lektion zu Textverarbeitung, Vorhersage und Lernen.", "Start Room 1":"Raum 1 starten", "Continue adventure":"Abenteuer fortsetzen", "Choose an unlocked room. Completed rooms can be replayed.":"Wähle einen freigeschalteten Raum. Abgeschlossene Räume sind wiederholbar.",
    "The lock receives text as token pieces, not one whole block.":"Das Schloss erhält Text als Tokens, nicht als einen ganzen Block.", "Verified Qwen2.5 tokenizer":"Geprüfter Qwen2.5-Tokenizer", "Verified example":"Geprüftes Beispiel", "Different tokenizers may split the same text differently.":"Verschiedene Tokenizer können denselben Text unterschiedlich zerlegen.", "Which statement about tokenising &ldquo;unhelpful&rdquo; is the most accurate?":"Welche Aussage zur Tokenisierung von „unhelpful“ ist am genauesten?", "It depends on the tokenizer. Different tokenizers may split &ldquo;unhelpful&rdquo; differently.":"Es hängt vom Tokenizer ab. Verschiedene Tokenizer können „unhelpful“ unterschiedlich zerlegen.",
    "Door scanner offline":"Türscanner offline", "Activate context scanner":"Kontextscanner aktivieren", "Current context window":"Aktuelles Kontextfenster", "Inside the window = available context":"Im Fenster = verfügbarer Kontext", "Outside the window = may not be available right now":"Außerhalb = derzeit möglicherweise nicht verfügbar", "Which tokens are available to the model right now?":"Welche Tokens sind dem Modell jetzt verfügbar?", "Unlock context door":"Kontexttür öffnen",
    "Connection console offline":"Verbindungskonsole offline", "Activate connection scanner":"Verbindungsscanner aktivieren", "Focus token · opened":"Fokus-Token · opened", "Strong contribution":"Starker Beitrag", "Medium contribution":"Mittlerer Beitrag", "Weak contribution":"Schwacher Beitrag", "Which token is shown contributing the most information to &ldquo;opened&rdquo;?":"Welches Token trägt laut Darstellung am meisten zu „opened“ bei?", "Unlock connection door":"Verbindungstür öffnen",
    "Prediction console offline":"Vorhersagekonsole offline", "Run prediction machine":"Vorhersagemaschine starten", "Next-token signal":"Nächstes-Token-Signal", "Higher probability = more likely right now.":"Höhere Wahrscheinlichkeit = derzeit wahrscheinlicher.", "Which statement best matches the prediction shown by the machine?":"Welche Aussage passt am besten zur gezeigten Vorhersage?", "Unlock prediction door":"Vorhersagetür öffnen",
    "Training console offline":"Trainingskonsole offline", "Inspect training console":"Trainingskonsole prüfen", "Training records":"Trainingsaufzeichnungen", "Reveal prediction":"Vorhersage zeigen", "Why can the training examples change the toy model's later prediction?":"Warum können Trainingsbeispiele die spätere Vorhersage verändern?",
    "Power the Language Model Door":"Sprachmodelltür mit Energie versorgen", "Final room not ready":"Finaler Raum nicht bereit", "Final Lock":"Finales Schloss", "FINAL LOCK":"FINALES SCHLOSS", "Place crystals":"Kristalle platzieren", "Form final crystal":"Finalen Kristall formen", "Solve final lock":"Finales Schloss lösen", "Language Model Door":"Sprachmodelltür", "Waiting for crystals":"Warten auf Kristalle", "Collected crystals":"Gesammelte Kristalle", "Arrange the five ideas":"Fünf Ideen ordnen", "Empty slot":"Leerer Platz", "Reset cards":"Karten zurücksetzen", "Replay final puzzle":"Finales Rätsel wiederholen", "Solve Final Lock":"Finales Schloss lösen", "Door open":"Tür offen", "Ready to open":"Bereit zum Öffnen", "Final crystal formed":"Finaler Kristall geformt"
  }
};

const extendedReplacements = {
  zh: {
    "Final learning challenge":"最终学习挑战", "Room":"房间", "Start Room 1":"开始房间 1", "Continue adventure":"继续冒险",
    "Here is how the tokenizer used in LLM Explorer splits":"这是 LLM Explorer 使用的分词器的拆分方式：", "Start by checking the door.":"先检查门锁。", "Run the machine to see a verified tokenizer example.":"运行机器，查看已验证的分词器示例。", "Compare the three splits, choose one, then activate the lock. The exact boundaries come from this tokenizer.":"比较这些拆分方式，选择一项后启动门锁；准确边界取决于这个分词器。",
    "Guide robot holding the lookup ID":"拿着查找 ID 的引导机器人", "go?":"会去哪里？", "Find drawer 305.":"找到 305 号抽屉。", "Try another number":"试试另一个数字", "Open":"打开", "Drawer 305 opens":"305 号抽屉打开", "What did ID 305 actually do?":"ID 305 实际做了什么？",
    "The console is waiting for an inspection.":"控制台正在等待检查。", "The scanner can now reveal the tokens available to the model.":"扫描器现在可以显示模型可用的 Token。", "Context scanner active":"上下文扫描器已启动", "The glowing frame marks the current available context.":"发光框标记当前可用上下文。", "Context scanner":"上下文扫描器", "Activate the scanner to reveal which tokens are available right now.":"启动扫描器，显示当前可用的 Token。", "The lock only reads the tokens inside the glowing context window.":"门锁只读取发光上下文窗口内的 Token。", "The glowing frame shows the context available to the model right now. Now choose the matching group of tokens.":"发光框显示模型当前可用的上下文。请选择匹配的 Token 组。",
    "The door is receiving signals from several token positions.":"门正在接收来自多个 Token 位置的信号。", "The scanner can reveal the already-computed connection pattern.":"扫描器可以显示已经计算好的连接模式。", "Connection scanner active":"连接扫描器已启动", "The scanner has revealed the pattern. Now decode it to open the lock.":"扫描器已显示连接模式。解读它以打开门锁。", "Connection console":"连接控制台", "Something is feeding information into the locked token console.":"某些 Token 正在向锁定的控制台提供信息。", "Activate the scanner to reveal the connection pattern.":"启动扫描器以显示连接模式。", "Read the already-shown arrow thicknesses. You do not need to guess which word matters most.":"读取已经显示的箭头粗细，无需猜测哪个词最重要。",
    "Prediction complete.":"预测完成。", "One token has been added; to continue generating, the model would use the updated context and predict again.":"已添加一个 Token；继续生成时，模型会使用更新后的上下文再次预测。", "The door needs a next-token signal, but the prediction machine is offline.":"门锁需要下一个 Token 信号，但预测机器处于离线状态。", "The machine compares several possible next tokens before the door can respond.":"门锁响应前，机器会比较多个可能的下一个 Token。", "Prediction machine running":"预测机器运行中", "The probabilities are visible. Read what the machine is actually telling you.":"概率已显示。请准确阅读机器表达的信息。", "Prediction console":"预测控制台", "The locked door needs a next-token signal.":"锁定的门需要下一个 Token 信号。", "Run the prediction machine to reveal the probabilities.":"运行预测机器以显示概率。",
    "Its archive contains the evidence needed to restore the model's pattern.":"档案中包含恢复模型模式所需的证据。", "Training records found":"已找到训练记录", "The archive contains simplified records from the toy training system.":"档案包含玩具训练系统的简化记录。", "Pattern console online":"模式控制台已上线", "The records and later prediction are connected. Use them to unlock the final crystal.":"这些记录与之后的预测相关。利用它们解锁最后一枚水晶。", "These simplified examples were used by the toy training system earlier.":"玩具训练系统之前使用过这些简化示例。", "TEST RECORD":"测试记录", "Simplified · illustrative":"简化 · 示意", "Training archive console":"训练档案控制台", "The training console is offline. Inspect its records to see how the model learned.":"训练控制台离线。检查记录，了解模型如何学习。", "The console contains records from earlier training examples. Reveal the later prediction.":"控制台包含早期训练示例的记录。显示之后的预测。", "The examples affected what became more likely later. But why?":"这些示例影响了之后哪些结果更可能。为什么？",
    "Combining the five ideas...":"正在组合五个概念……", "Combine all five crystals to reveal the last challenge.":"组合全部五枚水晶，显示最后的挑战。"
  },
  fr: {
    "Final learning challenge":"Défi d’apprentissage final", "Room":"Salle", "Start Room 1":"Commencer la salle 1", "Continue adventure":"Continuer l’aventure",
    "Here is how the tokenizer used in LLM Explorer splits":"Voici le découpage du tokenizer utilisé dans LLM Explorer :", "Start by checking the door.":"Commence par inspecter la porte.", "Run the machine to see a verified tokenizer example.":"Lance la machine pour voir un exemple vérifié.", "Compare the three splits, choose one, then activate the lock. The exact boundaries come from this tokenizer.":"Compare les découpages, choisis-en un puis active le verrou ; les limites exactes dépendent de ce tokenizer.",
    "Guide robot holding the lookup ID":"Robot-guide tenant l’identifiant", "go?":"va-t-il ?", "Find drawer 305.":"Trouve le tiroir 305.", "Try another number":"Essaie un autre numéro", "Open":"Ouvrir", "Drawer 305 opens":"Le tiroir 305 s’ouvre", "What did ID 305 actually do?":"Quel était réellement le rôle de l’identifiant 305 ?",
    "The console is waiting for an inspection.":"La console attend d’être inspectée.", "The scanner can now reveal the tokens available to the model.":"Le scanner peut maintenant révéler les tokens disponibles.", "Context scanner active":"Scanner de contexte actif", "The glowing frame marks the current available context.":"Le cadre lumineux indique le contexte disponible.", "Context scanner":"Scanner de contexte", "Activate the scanner to reveal which tokens are available right now.":"Active le scanner pour révéler les tokens disponibles.", "The lock only reads the tokens inside the glowing context window.":"Le verrou ne lit que les tokens dans la fenêtre lumineuse.", "The glowing frame shows the context available to the model right now. Now choose the matching group of tokens.":"Le cadre montre le contexte disponible. Choisis maintenant le groupe correspondant.",
    "The door is receiving signals from several token positions.":"La porte reçoit des signaux de plusieurs positions de tokens.", "The scanner can reveal the already-computed connection pattern.":"Le scanner peut révéler le motif de connexions déjà calculé.", "Connection scanner active":"Scanner des connexions actif", "The scanner has revealed the pattern. Now decode it to open the lock.":"Le motif est visible. Décode-le pour ouvrir le verrou.", "Connection console":"Console des connexions", "Something is feeding information into the locked token console.":"Des positions de tokens alimentent la console verrouillée.", "Activate the scanner to reveal the connection pattern.":"Active le scanner pour révéler le motif.", "Read the already-shown arrow thicknesses. You do not need to guess which word matters most.":"Observe l’épaisseur des flèches ; inutile de deviner quel mot compte le plus.",
    "Prediction complete.":"Prédiction terminée.", "One token has been added; to continue generating, the model would use the updated context and predict again.":"Un token a été ajouté ; pour continuer, le modèle utiliserait le contexte mis à jour et prédirait encore.", "The door needs a next-token signal, but the prediction machine is offline.":"La porte a besoin d’un signal du token suivant, mais la machine est hors ligne.", "The machine compares several possible next tokens before the door can respond.":"La machine compare plusieurs tokens suivants possibles avant la réponse de la porte.", "Prediction machine running":"Machine de prédiction active", "The probabilities are visible. Read what the machine is actually telling you.":"Les probabilités sont visibles. Lis précisément ce qu’indique la machine.", "Prediction console":"Console de prédiction", "The locked door needs a next-token signal.":"La porte verrouillée exige un signal du token suivant.", "Run the prediction machine to reveal the probabilities.":"Lance la machine pour révéler les probabilités.",
    "Its archive contains the evidence needed to restore the model's pattern.":"Ses archives contiennent les éléments nécessaires pour restaurer le motif.", "Training records found":"Archives d’entraînement trouvées", "The archive contains simplified records from the toy training system.":"Les archives contiennent des données simplifiées du système jouet.", "Pattern console online":"Console des motifs active", "The records and later prediction are connected. Use them to unlock the final crystal.":"Les archives et la prédiction ultérieure sont liées. Utilise-les pour libérer le dernier cristal.", "These simplified examples were used by the toy training system earlier.":"Le système d’entraînement jouet a utilisé ces exemples simplifiés plus tôt.", "TEST RECORD":"ENREGISTREMENT TEST", "Simplified · illustrative":"Simplifié · illustratif", "Training archive console":"Console des archives d’entraînement", "The training console is offline. Inspect its records to see how the model learned.":"La console est hors ligne. Inspecte ses archives pour comprendre l’apprentissage.", "The console contains records from earlier training examples. Reveal the later prediction.":"La console contient des exemples d’entraînement antérieurs. Révèle la prédiction ultérieure.", "The examples affected what became more likely later. But why?":"Les exemples ont modifié ce qui est devenu plus probable. Pourquoi ?",
    "Combining the five ideas...":"Combinaison des cinq idées…", "Combine all five crystals to reveal the last challenge.":"Combine les cinq cristaux pour révéler le dernier défi."
  },
  de: {
    "Final learning challenge":"Finale Lernchallenge", "Room":"Raum", "Start Room 1":"Raum 1 starten", "Continue adventure":"Abenteuer fortsetzen",
    "Here is how the tokenizer used in LLM Explorer splits":"So zerlegt der in LLM Explorer verwendete Tokenizer:", "Start by checking the door.":"Prüfe zuerst die Tür.", "Run the machine to see a verified tokenizer example.":"Starte die Maschine für ein geprüftes Tokenizer-Beispiel.", "Compare the three splits, choose one, then activate the lock. The exact boundaries come from this tokenizer.":"Vergleiche die Aufteilungen, wähle eine und aktiviere das Schloss; die genauen Grenzen stammen von diesem Tokenizer.",
    "Guide robot holding the lookup ID":"Roboter-Guide mit der Nachschlage-ID", "go?":"hin?", "Find drawer 305.":"Finde Schublade 305.", "Try another number":"Andere Nummer versuchen", "Open":"Öffnen", "Drawer 305 opens":"Schublade 305 öffnet sich", "What did ID 305 actually do?":"Was bewirkte ID 305 tatsächlich?",
    "The console is waiting for an inspection.":"Die Konsole wartet auf eine Prüfung.", "The scanner can now reveal the tokens available to the model.":"Der Scanner kann nun die verfügbaren Tokens zeigen.", "Context scanner active":"Kontextscanner aktiv", "The glowing frame marks the current available context.":"Der leuchtende Rahmen markiert den verfügbaren Kontext.", "Context scanner":"Kontextscanner", "Activate the scanner to reveal which tokens are available right now.":"Aktiviere den Scanner, um die verfügbaren Tokens zu zeigen.", "The lock only reads the tokens inside the glowing context window.":"Das Schloss liest nur Tokens im leuchtenden Kontextfenster.", "The glowing frame shows the context available to the model right now. Now choose the matching group of tokens.":"Der Rahmen zeigt den aktuell verfügbaren Kontext. Wähle die passende Token-Gruppe.",
    "The door is receiving signals from several token positions.":"Die Tür erhält Signale von mehreren Token-Positionen.", "The scanner can reveal the already-computed connection pattern.":"Der Scanner kann das bereits berechnete Verbindungsmuster zeigen.", "Connection scanner active":"Verbindungsscanner aktiv", "The scanner has revealed the pattern. Now decode it to open the lock.":"Das Muster ist sichtbar. Entschlüssle es, um das Schloss zu öffnen.", "Connection console":"Verbindungskonsole", "Something is feeding information into the locked token console.":"Token-Positionen liefern Informationen an die gesperrte Konsole.", "Activate the scanner to reveal the connection pattern.":"Aktiviere den Scanner, um das Verbindungsmuster zu zeigen.", "Read the already-shown arrow thicknesses. You do not need to guess which word matters most.":"Lies die gezeigten Pfeilstärken ab; du musst nicht raten, welches Wort am wichtigsten ist.",
    "Prediction complete.":"Vorhersage abgeschlossen.", "One token has been added; to continue generating, the model would use the updated context and predict again.":"Ein Token wurde hinzugefügt; zum Fortsetzen würde das Modell den aktualisierten Kontext nutzen und erneut vorhersagen.", "The door needs a next-token signal, but the prediction machine is offline.":"Die Tür benötigt ein Nächstes-Token-Signal, doch die Maschine ist offline.", "The machine compares several possible next tokens before the door can respond.":"Die Maschine vergleicht mehrere mögliche nächste Tokens, bevor die Tür reagiert.", "Prediction machine running":"Vorhersagemaschine läuft", "The probabilities are visible. Read what the machine is actually telling you.":"Die Wahrscheinlichkeiten sind sichtbar. Lies genau, was die Maschine aussagt.", "Prediction console":"Vorhersagekonsole", "The locked door needs a next-token signal.":"Die gesperrte Tür benötigt ein Nächstes-Token-Signal.", "Run the prediction machine to reveal the probabilities.":"Starte die Vorhersagemaschine, um die Wahrscheinlichkeiten zu zeigen.",
    "Its archive contains the evidence needed to restore the model's pattern.":"Das Archiv enthält die Belege zum Wiederherstellen des Musters.", "Training records found":"Trainingsaufzeichnungen gefunden", "The archive contains simplified records from the toy training system.":"Das Archiv enthält vereinfachte Aufzeichnungen des Spielzeug-Trainingssystems.", "Pattern console online":"Musterkonsole online", "The records and later prediction are connected. Use them to unlock the final crystal.":"Aufzeichnungen und spätere Vorhersage hängen zusammen. Nutze sie für den letzten Kristall.", "These simplified examples were used by the toy training system earlier.":"Das Spielzeug-Trainingssystem nutzte diese vereinfachten Beispiele früher.", "TEST RECORD":"TESTAUFZEICHNUNG", "Simplified · illustrative":"Vereinfacht · veranschaulicht", "Training archive console":"Trainingsarchiv-Konsole", "The training console is offline. Inspect its records to see how the model learned.":"Die Trainingskonsole ist offline. Prüfe die Aufzeichnungen, um das Lernen zu verstehen.", "The console contains records from earlier training examples. Reveal the later prediction.":"Die Konsole enthält frühere Trainingsbeispiele. Zeige die spätere Vorhersage.", "The examples affected what became more likely later. But why?":"Die Beispiele beeinflussten, was später wahrscheinlicher wurde. Warum?",
    "Combining the five ideas...":"Die fünf Ideen werden kombiniert…", "Combine all five crystals to reveal the last challenge.":"Kombiniere alle fünf Kristalle, um die letzte Challenge zu zeigen."
  }
};

const commonEntries = Object.keys(commonKeys);
export const activeEscapeRoomEnglish = [...new Set([
  ...commonEntries,
  ...Object.keys(activeReplacements.zh),
  ...Object.keys(extendedReplacements.zh)
])];
export const escapeRoomRuntimeLocales = Object.fromEntries(["zh","fr","de"].map((language) => [language, {
  messages: {
    top: messages[language].top,
    common: messages[language].common,
    feedback: messages[language].feedback,
    exit: messages[language].exit,
    completion: messages[language].completion
  },
  fallbackMessages: {},
  replacements: {
    ...Object.fromEntries(commonEntries.map((source, index) => [source, sharedTranslations[language][index] || source])),
    ...Object.fromEntries(Object.entries(messages[language]).filter(([key]) => !["top", "common", "feedback", "exit", "completion"].includes(key))),
    ...activeReplacements[language],
    ...extendedReplacements[language]
  }
}]));
