const EN = {
  idTitle:"Tokens get IDs", idIntro:"After tokenisation, each token gets an ID. Think of it as a name tag the model can look up.", token:"Token", nameTag:"Token ID (name tag)", piece:"A piece of text.", justLabel:"The ID is just a label.", notMeaning:"305 does not mean ‘reader’. It is just a number.", example:"Simplified teaching example — real IDs depend on the model.",
  numbersTitle:"What happens after a token gets an ID?", numbersIntro:"The model uses the ID to find a set of learned numbers that help it notice patterns in language.", findNumbers:"Find learned numbers", learned:"These numbers were learned during training.", illustrative:"Illustrative numbers — not real model values.", point:"So what’s the point?", pointIntro:"These learned numbers help the LLM:", patterns:"See patterns in tokens", relations:"Understand relationships between tokens", predict:"Predict which token might come next", boundary:"Different models may use different IDs and different numbers for the same token.", sameIdea:"The idea is the same: text → tokens → IDs → learned numbers.",
  quizTitle:"Check the idea", quizIntro:"Three quick questions to see what you remember.", conceptCheckpoint:"Concept checkpoint", threeQuestions:"3 quick questions to see what you remember.", answerEach:"Answer each question, then check your answer.", yourProgress:"Your progress", questionLabel:"Question", questionOf:"Question {{current}} of {{total}}", completedLabel:"completed", takeTime:"Take your time!", readCarefully:"Read each question carefully.", qwenExample:"A real split from the lesson’s Qwen tokenizer", qwenTokenizer:"Qwen tokenizer", qwenVerifiedIds:"Verified token IDs: 33865 · 7995 · 10070", checkAnswer:"Check answer", tryAgain:"Try again", nextQuestion:"Next question", returnToLatest:"Return to current question", finishCheckpoint:"Finish checkpoint", continue:"Continue", correctLabel:"Correct", incorrectLabel:"Incorrect", niceWork:"Nice work!", completionText:"You’ve checked the key ideas from this lesson.", completedIdeas:["Tokens can be different-sized pieces of text","Different tokenizers can split text differently","Token IDs are labels"], idReminder:"305 is a label — it does not mean “reader”.", checkpointQuestions:[
    {prompt:"What can a token be?",options:["Only a complete word","A whole word, part of a word, or punctuation","Only a sentence","Only a number"],correct:1,correctFeedback:"Exactly! A token can be a whole word, part of a word, or punctuation.",incorrectFeedback:"Not quite. Tokens are not always complete words. Think about how longer words can be split into smaller pieces."},
    {prompt:"Do two tokenizers always have to split the same text in exactly the same way?",options:["Yes — there is only one correct split","No — different tokenizers can split the same text differently","Only if the sentence is very long","Only punctuation can be different"],correct:1,correctFeedback:"Exactly! Different tokenizers can use different token pieces. Different doesn’t mean wrong.",incorrectFeedback:"Not quite. A tokenizer follows the token system its model was built with, so the same text can be split differently."},
    {prompt:"What is a token ID used for?",options:["It shows how important a token is","It contains the meaning of the token","It acts like a label the model can use to identify the token","It tells us how likely the token is to come next"],correct:2,correctFeedback:"Right! A token ID is like a name tag. The number itself does not contain the token’s meaning.",incorrectFeedback:"Not quite. An ID is not a meaning, probability, or importance score. Think of it as a name tag."}
  ]
};
const ZH = {...EN,idTitle:"Token 会获得 ID",idIntro:"分词后，每个 Token 都会获得一个 ID。可以把它想成模型用来查找的姓名牌。",nameTag:"Token ID（姓名牌）",piece:"一小段文本。",justLabel:"ID 只是一个标签。",notMeaning:"305 并不表示“reader”的含义，它只是一个数字。",example:"简化教学示例——真实 ID 取决于具体模型。",numbersTitle:"Token 获得 ID 后会发生什么？",numbersIntro:"模型用 ID 找到一组训练中学到的数字，帮助它发现语言模式。",findNumbers:"查找学到的数字",learned:"这些数字是在训练中学到的。",illustrative:"示意数字——不是真实模型数值。",point:"这有什么用？",pointIntro:"这些数字帮助 LLM：",patterns:"发现 Token 中的模式",relations:"理解 Token 之间的关系",predict:"预测下一个可能的 Token",boundary:"不同模型可能给同一 Token 使用不同的 ID 和数字。",sameIdea:"核心过程相同：文本 → Token → ID → 学到的数字。",quizTitle:"检查你学会了什么",quizIntro:"三个小问题，看看你记住了多少。",conceptCheckpoint:"概念检查",threeQuestions:"用 3 个小问题检查你记住了多少。",answerEach:"回答每个问题，然后检查答案。",yourProgress:"你的进度",questionLabel:"问题",questionOf:"第 {{current}} 题，共 {{total}} 题",completedLabel:"已完成",takeTime:"慢慢来！",readCarefully:"请仔细阅读每个问题。",qwenExample:"课程中 Qwen tokenizer 的真实切分",qwenTokenizer:"Qwen tokenizer",qwenVerifiedIds:"已验证的 Token ID：33865 · 7995 · 10070",checkAnswer:"检查答案",tryAgain:"再试一次",nextQuestion:"下一题",returnToLatest:"返回当前问题",finishCheckpoint:"完成检查",continue:"继续",correctLabel:"正确",incorrectLabel:"不正确",niceWork:"做得好！",completionText:"你已经检查了本课的核心概念。",completedIdeas:["Token 可以是不同大小的文本片段","不同 tokenizer 可以用不同方式切分文本","Token ID 是标签"],idReminder:"305 是标签——它并不表示“reader”的含义。",checkpointQuestions:[
    {prompt:"Token 可以是什么？",options:["只能是完整单词","完整单词、单词的一部分或标点符号","只能是句子","只能是数字"],correct:1,correctFeedback:"完全正确！Token 可以是完整单词、单词的一部分或标点符号。",incorrectFeedback:"还不完全对。Token 不一定是完整单词。想想较长的单词可以怎样被切分成更小的片段。"},
    {prompt:"两个 tokenizer 是否必须以完全相同的方式切分同一段文本？",options:["是——只有一种正确切分方式","不是——不同 tokenizer 可以用不同方式切分同一文本","只有句子很长时才会不同","只有标点符号可能不同"],correct:1,correctFeedback:"完全正确！不同 tokenizer 可以使用不同的 Token 片段。不同并不代表错误。",incorrectFeedback:"还不完全对。Tokenizer 会遵循其模型采用的 Token 系统，因此同一文本可以有不同的切分方式。"},
    {prompt:"Token ID 有什么作用？",options:["表示一个 Token 有多重要","包含 Token 的含义","像标签一样帮助模型识别 Token","表示该 Token 接下来出现的概率"],correct:2,correctFeedback:"正确！Token ID 就像姓名牌；数字本身不包含 Token 的含义。",incorrectFeedback:"还不完全对。ID 不是含义、概率或重要性分数，可以把它理解成姓名牌。"}
  ],check:"检查答案",retry:"再试一次",correct:"很好——你已经连起了 Token、ID 和学到的数字。",incomplete:"再看看标出的题目。",questions:[["Token 可以是什么？",["只能是完整单词","单词、单词的一部分或标点","图片"],1],["两个 tokenizer 会用不同方式切分同一文本吗？",["会","不会"],0],["Token ID 是什么？",["姓名牌式的标签","Token 的含义","概率"],0],["ID 305 表示 reader 的含义吗？",["是","不是——数字只是标签"],1],["模型为什么查找学到的数字？",["装饰 Token","发现关系并预测接下来可能出现的内容","只计算字母"],1]]};
const FR={...EN,idTitle:"Les tokens reçoivent des identifiants",idIntro:"Après la tokenisation, chaque token reçoit un identifiant. Imagine-le comme une étiquette que le modèle peut rechercher.",nameTag:"Identifiant du token (étiquette)",piece:"Un morceau de texte.",justLabel:"L’identifiant est seulement une étiquette.",notMeaning:"305 ne signifie pas « reader ». C’est seulement un nombre.",example:"Exemple pédagogique simplifié — les vrais identifiants dépendent du modèle.",numbersTitle:"Que se passe-t-il après qu’un token reçoit un identifiant ?",numbersIntro:"Le modèle utilise l’identifiant pour trouver un ensemble de nombres appris qui l’aident à repérer des motifs dans la langue.",findNumbers:"Trouver les nombres appris",learned:"Ces nombres ont été appris pendant l’entraînement.",illustrative:"Nombres illustratifs — pas de vraies valeurs du modèle.",point:"À quoi cela sert-il ?",pointIntro:"Ces nombres appris aident le LLM à :",patterns:"Repérer des motifs dans les tokens",relations:"Comprendre les relations entre les tokens",predict:"Prédire quel token pourrait suivre",boundary:"Différents modèles peuvent utiliser différents identifiants et nombres pour le même token.",sameIdea:"L’idée reste la même : texte → tokens → identifiants → nombres appris.",quizTitle:"Vérifie ce que tu as appris",quizIntro:"Trois questions rapides pour vérifier ce que tu as retenu.",conceptCheckpoint:"Point de contrôle",threeQuestions:"3 questions rapides pour vérifier ce que tu as retenu.",answerEach:"Réponds à chaque question, puis vérifie ta réponse.",yourProgress:"Ta progression",questionLabel:"Question",questionOf:"Question {{current}} sur {{total}}",completedLabel:"terminée",takeTime:"Prends ton temps !",readCarefully:"Lis attentivement chaque question.",qwenExample:"Un découpage réel du tokenizer Qwen vu dans la leçon",qwenTokenizer:"Tokenizer Qwen",qwenVerifiedIds:"Identifiants de tokens vérifiés : 33865 · 7995 · 10070",checkAnswer:"Vérifier la réponse",tryAgain:"Réessayer",nextQuestion:"Question suivante",returnToLatest:"Revenir à la question actuelle",finishCheckpoint:"Terminer le contrôle",continue:"Continuer",correctLabel:"Correct",incorrectLabel:"Incorrect",niceWork:"Bravo !",completionText:"Tu as vérifié les idées essentielles de cette leçon.",completedIdeas:["Les tokens peuvent être des morceaux de texte de tailles différentes","Différents tokenizers peuvent découper un texte différemment","Les identifiants de tokens sont des étiquettes"],idReminder:"305 est une étiquette : il ne signifie pas « reader ».",checkpointQuestions:[
    {prompt:"Que peut être un token ?",options:["Seulement un mot entier","Un mot entier, une partie de mot ou un signe de ponctuation","Seulement une phrase","Seulement un nombre"],correct:1,correctFeedback:"Exactement ! Un token peut être un mot entier, une partie de mot ou un signe de ponctuation.",incorrectFeedback:"Pas tout à fait. Les tokens ne sont pas toujours des mots entiers. Pense à la manière dont les mots longs peuvent être découpés en morceaux plus petits."},
    {prompt:"Deux tokenizers doivent-ils toujours découper le même texte exactement de la même façon ?",options:["Oui — il n’existe qu’un seul découpage correct","Non — différents tokenizers peuvent découper le même texte différemment","Seulement si la phrase est très longue","Seule la ponctuation peut varier"],correct:1,correctFeedback:"Exactement ! Différents tokenizers peuvent utiliser des morceaux différents. Différent ne veut pas dire incorrect.",incorrectFeedback:"Pas tout à fait. Un tokenizer suit le système de tokens pour lequel son modèle a été conçu ; le même texte peut donc être découpé différemment."},
    {prompt:"À quoi sert un identifiant de token ?",options:["À indiquer l’importance d’un token","À contenir le sens du token","À servir d’étiquette permettant au modèle d’identifier le token","À indiquer la probabilité que le token apparaisse ensuite"],correct:2,correctFeedback:"Exact ! Un identifiant de token ressemble à une étiquette. Le nombre lui-même ne contient pas le sens du token.",incorrectFeedback:"Pas tout à fait. Un identifiant n’est ni un sens, ni une probabilité, ni un score d’importance. Considère-le comme une étiquette."}
  ],check:"Vérifier les réponses",retry:"Réessayer",correct:"Bravo — tu as relié tokens, identifiants et nombres appris.",incomplete:"Regarde encore les questions signalées.",questions:[["Que peut être un token ?",["Seulement un mot entier","Un mot, une partie de mot ou un signe de ponctuation","Une image"],1],["Deux tokenizers peuvent-ils découper le même texte différemment ?",["Oui","Non"],0],["Qu’est-ce qu’un identifiant de token ?",["Une étiquette","Le sens du token","Une probabilité"],0],["L’identifiant 305 signifie-t-il « reader » ?",["Oui","Non — le nombre est seulement une étiquette"],1],["Pourquoi le modèle trouve-t-il des nombres appris ?",["Pour décorer le token","Pour repérer des relations et prédire la suite","Seulement pour compter les lettres"],1]]};
const DE={...EN,idTitle:"Tokens erhalten IDs",idIntro:"Nach der Tokenisierung erhält jedes Token eine ID. Stell sie dir wie ein Namensschild vor, das das Modell nachschlagen kann.",nameTag:"Token-ID (Namensschild)",piece:"Ein Textstück.",justLabel:"Die ID ist nur ein Etikett.",notMeaning:"305 bedeutet nicht „reader“. Es ist nur eine Zahl.",example:"Vereinfachtes Lernbeispiel — echte IDs hängen vom Modell ab.",numbersTitle:"Was passiert, nachdem ein Token eine ID erhält?",numbersIntro:"Das Modell verwendet die ID, um gelernte Zahlen zu finden, die ihm helfen, Sprachmuster zu erkennen.",findNumbers:"Gelernte Zahlen finden",learned:"Diese Zahlen wurden beim Training gelernt.",illustrative:"Beispielzahlen — keine echten Modellwerte.",point:"Wozu ist das gut?",pointIntro:"Diese gelernten Zahlen helfen dem LLM:",patterns:"Muster in Tokens zu erkennen",relations:"Beziehungen zwischen Tokens zu verstehen",predict:"Das nächste mögliche Token vorherzusagen",boundary:"Verschiedene Modelle können für dasselbe Token verschiedene IDs und Zahlen verwenden.",sameIdea:"Die Idee bleibt gleich: Text → Tokens → IDs → gelernte Zahlen.",quizTitle:"Prüfe, was du gelernt hast",quizIntro:"Drei kurze Fragen zeigen, was du behalten hast.",conceptCheckpoint:"Wissenscheck",threeQuestions:"3 kurze Fragen zeigen, was du behalten hast.",answerEach:"Beantworte jede Frage und prüfe danach deine Antwort.",yourProgress:"Dein Fortschritt",questionLabel:"Frage",questionOf:"Frage {{current}} von {{total}}",completedLabel:"abgeschlossen",takeTime:"Nimm dir Zeit!",readCarefully:"Lies jede Frage sorgfältig.",qwenExample:"Eine echte Aufteilung mit dem Qwen-Tokenizer aus der Lektion",qwenTokenizer:"Qwen-Tokenizer",qwenVerifiedIds:"Verifizierte Token-IDs: 33865 · 7995 · 10070",checkAnswer:"Antwort prüfen",tryAgain:"Noch einmal",nextQuestion:"Nächste Frage",returnToLatest:"Zur aktuellen Frage zurückkehren",finishCheckpoint:"Wissenscheck abschließen",continue:"Weiter",correctLabel:"Richtig",incorrectLabel:"Falsch",niceWork:"Gut gemacht!",completionText:"Du hast die wichtigsten Ideen dieser Lektion überprüft.",completedIdeas:["Tokens können unterschiedlich große Textstücke sein","Verschiedene Tokenizer können Text unterschiedlich aufteilen","Token-IDs sind Etiketten"],idReminder:"305 ist ein Etikett — die Zahl bedeutet nicht „reader“.",checkpointQuestions:[
    {prompt:"Was kann ein Token sein?",options:["Nur ein vollständiges Wort","Ein vollständiges Wort, ein Wortteil oder ein Satzzeichen","Nur ein Satz","Nur eine Zahl"],correct:1,correctFeedback:"Genau! Ein Token kann ein vollständiges Wort, ein Wortteil oder ein Satzzeichen sein.",incorrectFeedback:"Nicht ganz. Tokens sind nicht immer vollständige Wörter. Überlege, wie längere Wörter in kleinere Teile zerlegt werden können."},
    {prompt:"Müssen zwei Tokenizer denselben Text immer genau gleich aufteilen?",options:["Ja — es gibt nur eine richtige Aufteilung","Nein — verschiedene Tokenizer können denselben Text unterschiedlich aufteilen","Nur wenn der Satz sehr lang ist","Nur Satzzeichen können unterschiedlich sein"],correct:1,correctFeedback:"Genau! Verschiedene Tokenizer können unterschiedliche Token-Teile verwenden. Anders bedeutet nicht falsch.",incorrectFeedback:"Nicht ganz. Ein Tokenizer folgt dem Token-System, für das sein Modell entwickelt wurde; daher kann derselbe Text unterschiedlich aufgeteilt werden."},
    {prompt:"Wozu dient eine Token-ID?",options:["Sie zeigt, wie wichtig ein Token ist","Sie enthält die Bedeutung des Tokens","Sie dient als Etikett, mit dem das Modell das Token identifizieren kann","Sie zeigt, wie wahrscheinlich das Token als Nächstes ist"],correct:2,correctFeedback:"Richtig! Eine Token-ID ist wie ein Namensschild. Die Zahl selbst enthält nicht die Bedeutung des Tokens.",incorrectFeedback:"Nicht ganz. Eine ID ist weder Bedeutung noch Wahrscheinlichkeit oder Wichtigkeitswert. Stell sie dir als Namensschild vor."}
  ],check:"Antworten prüfen",retry:"Noch einmal",correct:"Gut gemacht — du hast Tokens, IDs und gelernte Zahlen verbunden.",incomplete:"Sieh dir die markierten Fragen noch einmal an.",questions:[["Was kann ein Token sein?",["Nur ein ganzes Wort","Ein Wort, Wortteil oder Satzzeichen","Ein Bild"],1],["Können zwei Tokenizer denselben Text unterschiedlich aufteilen?",["Ja","Nein"],0],["Was ist eine Token-ID?",["Ein Namensschild","Die Bedeutung des Tokens","Eine Wahrscheinlichkeit"],0],["Bedeutet ID 305 „reader“?",["Ja","Nein — die Zahl ist nur ein Etikett"],1],["Warum sucht das Modell gelernte Zahlen?",["Um das Token zu dekorieren","Um Beziehungen zu erkennen und die Fortsetzung vorherzusagen","Nur um Buchstaben zu zählen"],1]]};
const COPY={en:EN,zh:ZH,fr:FR,de:DE};
const TOKEN_ID_SAMPLE_COPY = {
  en: { sampleToken: "reader" },
  zh: { sampleToken: "读者", notMeaning: "305 并不表示“读者”的含义，它只是一个数字。", idReminder: "305 是标签——它并不表示“读者”的含义。" },
  fr: { sampleToken: "lecteur", notMeaning: "305 ne signifie pas « lecteur ». C’est seulement un nombre.", idReminder: "305 est une étiquette : il ne signifie pas « lecteur »." },
  de: { sampleToken: "Leser", notMeaning: "305 bedeutet nicht „Leser“. Es ist nur eine Zahl.", idReminder: "305 ist ein Etikett — die Zahl bedeutet nicht „Leser“." }
};
export function getLesson1JourneyCopy(language){const locale=COPY[language]?language:"en";return {...COPY[locale],...TOKEN_ID_SAMPLE_COPY[locale]};}
